// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: lilygo_tdisplay_s3_04

#include "../ui.h"


// COMPONENT SmallDataPanel

lv_obj_t * ui_SmallDataPanel_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_SmallDataPanel;
    cui_SmallDataPanel = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_SmallDataPanel, lv_pct(50));
    lv_obj_set_height(cui_SmallDataPanel, lv_pct(100));
    lv_obj_set_x(cui_SmallDataPanel, 50);
    lv_obj_set_y(cui_SmallDataPanel, 0);
    lv_obj_clear_flag(cui_SmallDataPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_SmallDataPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_SmallDataPanel, lv_color_hex(0x44B8D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_SmallDataPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_SmallDataPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_SmallDataPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_SmallDataPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_SmallDataPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_SmallDataPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(cui_SmallDataPanel, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_SmallDataPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_InfoLabel;
    cui_InfoLabel = lv_label_create(cui_SmallDataPanel);
    lv_obj_set_width(cui_InfoLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_InfoLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_InfoLabel, 4);
    lv_obj_set_y(cui_InfoLabel, -6);
    lv_obj_set_align(cui_InfoLabel, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(cui_InfoLabel, "10sRUN");
    lv_obj_set_style_text_font(cui_InfoLabel, &ui_font_OswaldRegular12p4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_InfoLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_InfoLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_DataLabel;
    cui_DataLabel = lv_label_create(cui_SmallDataPanel);
    lv_obj_set_width(cui_DataLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_DataLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(cui_DataLabel, 1);
    lv_obj_set_x(cui_DataLabel, lv_pct(10));
    lv_obj_set_align(cui_DataLabel, LV_ALIGN_CENTER);
    lv_label_set_text(cui_DataLabel, "125.97");
    lv_obj_set_style_bg_color(cui_DataLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_DataLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_SMALLDATAPANEL_NUM);
    children[UI_COMP_SMALLDATAPANEL_SMALLDATAPANEL] = cui_SmallDataPanel;
    children[UI_COMP_SMALLDATAPANEL_INFOLABEL] = cui_InfoLabel;
    children[UI_COMP_SMALLDATAPANEL_DATALABEL] = cui_DataLabel;
    lv_obj_add_event_cb(cui_SmallDataPanel, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_SmallDataPanel, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_SmallDataPanel_create_hook(cui_SmallDataPanel);
    return cui_SmallDataPanel;
}

