// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: lilygo_tdisplay_s3_04

#include "../ui.h"

void ui_StatsScreen_screen_init(void)
{
    ui_StatsScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_StatsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_StatsStatusPanelWrapper = lv_obj_create(ui_StatsScreen);
    lv_obj_set_width(ui_StatsStatusPanelWrapper, lv_pct(100));
    lv_obj_set_height(ui_StatsStatusPanelWrapper, lv_pct(15));
    lv_obj_set_align(ui_StatsStatusPanelWrapper, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_StatsStatusPanelWrapper, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StatsStatusPanelWrapper, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsStatusPanelWrapper, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsStatusPanelWrapper, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_StatsStatusPanelWrapper, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_StatsStatusPanelWrapper, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_StatsStatusPanelWrapper, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_StatsStatusPanelWrapper, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatStatusPanel = ui_StatusPanel_create(ui_StatsStatusPanelWrapper);
    lv_obj_set_x(ui_StatStatusPanel, 0);
    lv_obj_set_y(ui_StatStatusPanel, 0);





    ui_StatsPanel2Row = lv_obj_create(ui_StatsScreen);
    lv_obj_set_width(ui_StatsPanel2Row, lv_pct(100));
    lv_obj_set_height(ui_StatsPanel2Row, lv_pct(85));
    lv_obj_set_x(ui_StatsPanel2Row, 0);
    lv_obj_set_y(ui_StatsPanel2Row, -13);
    lv_obj_set_align(ui_StatsPanel2Row, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StatsPanel2Row, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_StatsPanel2Row, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StatsPanel2Row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel2Row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_StatsPanel2Row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_StatsPanel2Row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_StatsPanel2Row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_StatsPanel2Row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StatsPanel2Row, &ui_font_OswaldRegular48p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Stats2Row1FullPanel = ui_BigDataPanel_create(ui_StatsPanel2Row);
    lv_obj_set_width(ui_Stats2Row1FullPanel, lv_pct(100));
    lv_obj_set_height(ui_Stats2Row1FullPanel, lv_pct(62));
    lv_obj_set_x(ui_Stats2Row1FullPanel, 0);
    lv_obj_set_y(ui_Stats2Row1FullPanel, 0);
    lv_obj_set_style_border_width(ui_Stats2Row1FullPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Stats2Row1FullPanel, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_x(ui_comp_get_child(ui_Stats2Row1FullPanel, UI_COMP_BIGDATAPANEL_INFOLABEL), -267);
    lv_obj_set_y(ui_comp_get_child(ui_Stats2Row1FullPanel, UI_COMP_BIGDATAPANEL_INFOLABEL), -14);

    lv_obj_set_x(ui_comp_get_child(ui_Stats2Row1FullPanel, UI_COMP_BIGDATAPANEL_DATALABEL), 0);
    lv_obj_set_y(ui_comp_get_child(ui_Stats2Row1FullPanel, UI_COMP_BIGDATAPANEL_DATALABEL), 3);
    lv_obj_set_style_text_font(ui_comp_get_child(ui_Stats2Row1FullPanel, UI_COMP_BIGDATAPANEL_DATALABEL),
                               &ui_font_OswaldRegular84p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Stats2Row2Panel = lv_obj_create(ui_StatsPanel2Row);
    lv_obj_set_width(ui_Stats2Row2Panel, lv_pct(100));
    lv_obj_set_height(ui_Stats2Row2Panel, lv_pct(41));
    lv_obj_set_x(ui_Stats2Row2Panel, 0);
    lv_obj_set_y(ui_Stats2Row2Panel, lv_pct(62));
    lv_obj_clear_flag(ui_Stats2Row2Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Stats2Row2Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Stats2Row2Panel, lv_color_hex(0x44B8D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Stats2Row2Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Stats2Row2Panel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Stats2Row2Panel, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Stats2Row2Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Stats2Row2Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Stats2Row2Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Stats2Row2Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Stats2Row2LeftPanel = ui_SmallDataPanel_create(ui_Stats2Row2Panel);
    lv_obj_set_x(ui_Stats2Row2LeftPanel, 0);
    lv_obj_set_y(ui_Stats2Row2LeftPanel, 0);
    lv_obj_set_style_border_color(ui_Stats2Row2LeftPanel, lv_color_hex(0x44B8D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Stats2Row2LeftPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Stats2Row2LeftPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Stats2Row2LeftPanel, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Stats2Row2RightPanel = ui_SmallDataPanel_create(ui_Stats2Row2Panel);
    lv_obj_set_x(ui_Stats2Row2RightPanel, 161);
    lv_obj_set_y(ui_Stats2Row2RightPanel, 0);
    lv_obj_set_style_border_color(ui_Stats2Row2RightPanel, lv_color_hex(0x44B8D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Stats2Row2RightPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_StatsPanel3Row = lv_obj_create(ui_StatsScreen);
    lv_obj_set_width(ui_StatsPanel3Row, lv_pct(100));
    lv_obj_set_height(ui_StatsPanel3Row, lv_pct(85));
    lv_obj_clear_flag(ui_StatsPanel3Row, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StatsPanel3Row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_StatsPanel3Row, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StatsPanel3Row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel3Row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_StatsPanel3Row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_StatsPanel3Row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_StatsPanel3Row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_StatsPanel3Row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StatsPanel3Row, &ui_font_OswaldRegular48p4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Stats3Row1Panel = lv_obj_create(ui_StatsPanel3Row);
    lv_obj_set_width(ui_Stats3Row1Panel, lv_pct(100));
    lv_obj_set_height(ui_Stats3Row1Panel, lv_pct(34));
    lv_obj_clear_flag(ui_Stats3Row1Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Stats3Row1Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Stats3Row1Panel, lv_color_hex(0x44B8D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Stats3Row1Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Stats3Row1Panel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Stats3Row1Panel, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Stats3Row1Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Stats3Row1Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Stats3Row1Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Stats3Row1Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Stats3Row1LeftPanel = ui_SmallDataPanel_create(ui_Stats3Row1Panel);
    lv_obj_set_x(ui_Stats3Row1LeftPanel, 0);
    lv_obj_set_y(ui_Stats3Row1LeftPanel, 0);
    lv_obj_set_style_border_color(ui_Stats3Row1LeftPanel, lv_color_hex(0x44B8D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Stats3Row1LeftPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Stats3Row1LeftPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Stats3Row1LeftPanel, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Stats3Row1RightPanel = ui_SmallDataPanel_create(ui_Stats3Row1Panel);
    lv_obj_set_y(ui_Stats3Row1RightPanel, 0);
    lv_obj_set_x(ui_Stats3Row1RightPanel, lv_pct(50));
    lv_obj_set_style_border_color(ui_Stats3Row1RightPanel, lv_color_hex(0x44B8D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Stats3Row1RightPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Stats3Row2Panel = lv_obj_create(ui_StatsPanel3Row);
    lv_obj_set_width(ui_Stats3Row2Panel, lv_pct(100));
    lv_obj_set_height(ui_Stats3Row2Panel, lv_pct(34));
    lv_obj_set_x(ui_Stats3Row2Panel, 0);
    lv_obj_set_y(ui_Stats3Row2Panel, lv_pct(34));
    lv_obj_clear_flag(ui_Stats3Row2Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Stats3Row2Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Stats3Row2Panel, lv_color_hex(0x44B8D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Stats3Row2Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Stats3Row2Panel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Stats3Row2Panel, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Stats3Row2Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Stats3Row2Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Stats3Row2Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Stats3Row2Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Stats3Row2LeftPanel = ui_SmallDataPanel_create(ui_Stats3Row2Panel);
    lv_obj_set_x(ui_Stats3Row2LeftPanel, 0);
    lv_obj_set_y(ui_Stats3Row2LeftPanel, 0);
    lv_obj_set_style_border_color(ui_Stats3Row2LeftPanel, lv_color_hex(0x44B8D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Stats3Row2LeftPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Stats3Row2LeftPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Stats3Row2LeftPanel, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Stats3Row2RightPanel = ui_SmallDataPanel_create(ui_Stats3Row2Panel);
    lv_obj_set_y(ui_Stats3Row2RightPanel, 0);
    lv_obj_set_x(ui_Stats3Row2RightPanel, lv_pct(50));
    lv_obj_set_style_border_color(ui_Stats3Row2RightPanel, lv_color_hex(0x44B8D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Stats3Row2RightPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Stats3Row3Panel = lv_obj_create(ui_StatsPanel3Row);
    lv_obj_set_width(ui_Stats3Row3Panel, lv_pct(100));
    lv_obj_set_height(ui_Stats3Row3Panel, lv_pct(35));
    lv_obj_set_x(ui_Stats3Row3Panel, 0);
    lv_obj_set_y(ui_Stats3Row3Panel, lv_pct(67));
    lv_obj_clear_flag(ui_Stats3Row3Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Stats3Row3Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Stats3Row3Panel, lv_color_hex(0x44B8D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Stats3Row3Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Stats3Row3Panel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Stats3Row3Panel, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Stats3Row3Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Stats3Row3Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Stats3Row3Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Stats3Row3Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Stats3Row3LeftPanel = ui_SmallDataPanel_create(ui_Stats3Row3Panel);
    lv_obj_set_x(ui_Stats3Row3LeftPanel, 0);
    lv_obj_set_y(ui_Stats3Row3LeftPanel, 0);
    lv_obj_set_style_border_color(ui_Stats3Row3LeftPanel, lv_color_hex(0x44B8D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Stats3Row3LeftPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Stats3Row3LeftPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Stats3Row3LeftPanel, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Stats3Row3RightPanel = ui_SmallDataPanel_create(ui_Stats3Row3Panel);
    lv_obj_set_y(ui_Stats3Row3RightPanel, 0);
    lv_obj_set_x(ui_Stats3Row3RightPanel, lv_pct(50));
    lv_obj_set_style_border_color(ui_Stats3Row3RightPanel, lv_color_hex(0x44B8D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Stats3Row3RightPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



}
