// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: lilygo_tdisplay_s3_04

#include "ui.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_SpeedScreen
lv_obj_t * ui_SpeedPanel;
lv_obj_t * ui_SpeedMainPanel;
lv_obj_t * ui_SpeedStatusPanelWrapper;
lv_obj_t * ui_SpeedStatusPanel;
lv_obj_t * ui_SpeedSecondaryPanel;
lv_obj_t * ui_LeftPanel;
lv_obj_t * ui_RightPanel;
lv_obj_t * ui_Speed1Panel;
lv_obj_t * ui_Speed1MainPanel;
lv_obj_t * ui_Speed1SecondaryPanel;
lv_obj_t * ui_RunBar;
lv_obj_t * ui_MaxBar;
lv_obj_t * ui_MaxInfoLabel;
lv_obj_t * ui_RunInfoLabel;
lv_obj_t * ui_RunLabel;
lv_obj_t * ui_MaxLabel;


// SCREEN: ui_InfoScreen
lv_obj_t * ui_InfoStatusPanelWrapper;
lv_obj_t * ui_InfoStatusPanel;
lv_obj_t * ui_InfoMainPanel;
lv_obj_t * ui_MainImage;
lv_obj_t * ui_MainLabel;
lv_obj_t * ui_MainLowerLabel;
lv_obj_t * ui_InfoInitPanel;
lv_obj_t * ui_InitImage;
lv_obj_t * ui_InitLabel;


// SCREEN: ui_StatsScreen
lv_obj_t * ui_StatsStatusPanelWrapper;
lv_obj_t * ui_StatStatusPanel;
lv_obj_t * ui_StatsPanel2Row;
lv_obj_t * ui_Panel2Row1;
lv_obj_t * ui_Panel2Row2;
lv_obj_t * ui_StatsLeftPanel3;
lv_obj_t * ui_StatsRightPanel3;
lv_obj_t * ui_StatsPanel3Row;
lv_obj_t * ui_Panel3Row1;
lv_obj_t * ui_StatsLeftPanel;
lv_obj_t * ui_StatsRightPanel;
lv_obj_t * ui_Panel3Row2;
lv_obj_t * ui_StatsLeftPanel1;
lv_obj_t * ui_StatsRightPanel1;
lv_obj_t * ui_Panel3Row3;
lv_obj_t * ui_StatsLeftPanel2;
lv_obj_t * ui_StatsRightPanel2;
lv_obj_t * ui_StatsPanel4Row;
lv_obj_t * ui_Panel4Row1;
lv_obj_t * ui_StatsLeftPanel4;
lv_obj_t * ui_StatsRightPanel4;
lv_obj_t * ui_Panel4Row2;
lv_obj_t * ui_StatsLeftPanel5;
lv_obj_t * ui_StatsRightPanel5;
lv_obj_t * ui_Panel4Row3;
lv_obj_t * ui_StatsLeftPanel6;
lv_obj_t * ui_StatsRightPanel6;
lv_obj_t * ui_Panel4Row4;
lv_obj_t * ui_StatsLeftPanel7;
lv_obj_t * ui_StatsRightPanel7;
const lv_img_dsc_t * ui_imgset_battery_0_bar_fill0_wght400_grad0_opsz[1] = {&ui_img_battery_0_bar_fill0_wght400_grad0_opsz24_png};
const lv_img_dsc_t * ui_imgset_battery_horiz_000_fill0_wght400_grad0_opsz[1] = {&ui_img_battery_horiz_000_fill0_wght400_grad0_opsz24_png};
const lv_img_dsc_t * ui_imgset_navigation_fill0_wght400_grad0_opsz[1] = {&ui_img_navigation_fill0_wght400_grad0_opsz24_png};
const lv_img_dsc_t * ui_imgset_navigation_fill1_wght400_grad0_opsz[1] = {&ui_img_navigation_fill1_wght400_grad0_opsz24_png};
const lv_img_dsc_t * ui_imgset_radio_button_checked_fill0_wght400_grad0_opsz[1] = {&ui_img_radio_button_checked_fill0_wght400_grad0_opsz24_png};
const lv_img_dsc_t * ui_imgset_radio_button_partial_fill0_wght400_grad0_opsz[1] = {&ui_img_radio_button_partial_fill0_wght400_grad0_opsz24_png};
const lv_img_dsc_t * ui_imgset_radio_button_unchecked_fill0_wght400_grad0_opsz[1] = {&ui_img_radio_button_unchecked_fill0_wght400_grad0_opsz24_png};
const lv_img_dsc_t * ui_imgset_sd_card_fill0_wght400_grad0_opsz[1] = {&ui_img_sd_card_fill0_wght400_grad0_opsz24_png};
const lv_img_dsc_t * ui_imgset_sd_card_fill1_wght400_grad0_opsz[1] = {&ui_img_sd_card_fill1_wght400_grad0_opsz24_png};
const lv_img_dsc_t * ui_imgset_sd_card_alert_fill0_wght400_grad0_opsz[1] = {&ui_img_sd_card_alert_fill0_wght400_grad0_opsz24_png};
const lv_img_dsc_t * ui_imgset_sd_card_alert_fill1_wght400_grad0_opsz[1] = {&ui_img_sd_card_alert_fill1_wght400_grad0_opsz24_png};
const lv_img_dsc_t * ui_imgset_wifi_fill0_wght400_grad0_opsz[1] = {&ui_img_wifi_fill0_wght400_grad0_opsz24_png};

