// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: lilygo_tdisplay_s3_04

#ifndef _LILYGO_TDISPLAY_S3_04_UI_H
#define _LILYGO_TDISPLAY_S3_04_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "ui_common.h"


// SCREEN: ui_SpeedScreen
void ui_SpeedScreen_screen_init(void);
extern lv_obj_t * ui_SpeedScreen;
extern lv_obj_t * ui_SpeedPanel;
extern lv_obj_t * ui_SpeedMainPanel;
extern lv_obj_t * ui_SpeedStatusPanelWrapper;
extern lv_obj_t * ui_SpeedStatusPanel;
extern lv_obj_t * ui_SpeedSecondaryPanel;
extern lv_obj_t * ui_LeftPanel;
extern lv_obj_t * ui_RightPanel;
extern lv_obj_t * ui_Speed1Panel;
extern lv_obj_t * ui_Speed1MainPanel;
extern lv_obj_t * ui_Speed1SecondaryPanel;
extern lv_obj_t * ui_RunBar;
extern lv_obj_t * ui_MaxBar;
extern lv_obj_t * ui_MaxInfoLabel;
extern lv_obj_t * ui_RunInfoLabel;
extern lv_obj_t * ui_RunLabel;
extern lv_obj_t * ui_MaxLabel;
// SCREEN: ui_InfoScreen
void ui_InfoScreen_screen_init(void);
extern lv_obj_t * ui_InfoScreen;
extern lv_obj_t * ui_InfoStatusPanelWrapper;
extern lv_obj_t * ui_InfoStatusPanel;
extern lv_obj_t * ui_InfoMainPanel;
extern lv_obj_t * ui_MainImage;
extern lv_obj_t * ui_MainLabel;
extern lv_obj_t * ui_MainLowerLabel;
extern lv_obj_t * ui_InfoInitPanel;
extern lv_obj_t * ui_InitImage;
extern lv_obj_t * ui_InitLabel;
// SCREEN: ui_StatsScreen
void ui_StatsScreen_screen_init(void);
extern lv_obj_t * ui_StatsScreen;
extern lv_obj_t * ui_StatsStatusPanelWrapper;
extern lv_obj_t * ui_StatStatusPanel;
extern lv_obj_t * ui_StatsPanel2Row;
extern lv_obj_t * ui_Panel2Row1;
extern lv_obj_t * ui_Panel2Row2;
extern lv_obj_t * ui_StatsLeftPanel3;
extern lv_obj_t * ui_StatsRightPanel3;
extern lv_obj_t * ui_StatsPanel3Row;
extern lv_obj_t * ui_Panel3Row1;
extern lv_obj_t * ui_StatsLeftPanel;
extern lv_obj_t * ui_StatsRightPanel;
extern lv_obj_t * ui_Panel3Row2;
extern lv_obj_t * ui_StatsLeftPanel1;
extern lv_obj_t * ui_StatsRightPanel1;
extern lv_obj_t * ui_Panel3Row3;
extern lv_obj_t * ui_StatsLeftPanel2;
extern lv_obj_t * ui_StatsRightPanel2;
extern lv_obj_t * ui_StatsPanel4Row;
extern lv_obj_t * ui_Panel4Row1;
extern lv_obj_t * ui_StatsLeftPanel4;
extern lv_obj_t * ui_StatsRightPanel4;
extern lv_obj_t * ui_Panel4Row2;
extern lv_obj_t * ui_StatsLeftPanel5;
extern lv_obj_t * ui_StatsRightPanel5;
extern lv_obj_t * ui_Panel4Row3;
extern lv_obj_t * ui_StatsLeftPanel6;
extern lv_obj_t * ui_StatsRightPanel6;
extern lv_obj_t * ui_Panel4Row4;
extern lv_obj_t * ui_StatsLeftPanel7;
extern lv_obj_t * ui_StatsRightPanel7;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(
    ui_img_sd_card_alert_fill0_wght400_grad0_opsz24_png);    // assets/sd_card_alert_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(ui_img_navigation_fill0_wght400_grad0_opsz24_png);    // assets/navigation_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(ui_img_2129950171);    // assets/esp-gps-logo-v2-100px.png
LV_IMG_DECLARE(
    ui_img_battery_0_bar_fill0_wght400_grad0_opsz24_png);    // assets/battery_0_bar_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_battery_horiz_000_fill0_wght400_grad0_opsz24_png);    // assets/battery_horiz_000_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(ui_img_navigation_fill1_wght400_grad0_opsz24_png);    // assets/navigation_FILL1_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_radio_button_checked_fill0_wght400_grad0_opsz24_png);    // assets/radio_button_checked_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_radio_button_partial_fill0_wght400_grad0_opsz24_png);    // assets/radio_button_partial_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_radio_button_unchecked_fill0_wght400_grad0_opsz24_png);    // assets/radio_button_unchecked_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(ui_img_sd_card_fill0_wght400_grad0_opsz24_png);    // assets/sd_card_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(ui_img_sd_card_fill1_wght400_grad0_opsz24_png);    // assets/sd_card_FILL1_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_sd_card_alert_fill1_wght400_grad0_opsz24_png);    // assets/sd_card_alert_FILL1_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(ui_img_wifi_fill0_wght400_grad0_opsz24_png);    // assets/wifi_FILL0_wght400_GRAD0_opsz24.png


LV_FONT_DECLARE(ui_font_OswaldRegular108b4);
LV_FONT_DECLARE(ui_font_OswaldRegular120b4);
LV_FONT_DECLARE(ui_font_OswaldRegular12b4);
LV_FONT_DECLARE(ui_font_OswaldRegular12p2);
LV_FONT_DECLARE(ui_font_OswaldRegular24b4);
LV_FONT_DECLARE(ui_font_OswaldRegular36b4);
LV_FONT_DECLARE(ui_font_OswaldRegular48b4);
LV_FONT_DECLARE(ui_font_OswaldRegular84b4);



#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
