// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: lilygo_tdisplay_s3_status

#include "ui.h"

const ui_theme_variable_t _ui_theme_color_nearwhite[2] = {0xD5D5D5, 0xD5D5D5};
const ui_theme_variable_t _ui_theme_alpha_nearwhite[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_sbbackground[2] = {0x070707, 0x070707};
const ui_theme_variable_t _ui_theme_alpha_sbbackground[2] = {255, 255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;

void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

