// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: lilygo_tdisplay_s3_status

#include "../ui.h"


// COMPONENT StatusPanel

lv_obj_t *ui_StatusPanel_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_StatusPanel;
cui_StatusPanel = lv_obj_create(comp_parent);
lv_obj_set_width( cui_StatusPanel, lv_pct(100));
lv_obj_set_height( cui_StatusPanel, lv_pct(100));
lv_obj_set_align( cui_StatusPanel, LV_ALIGN_BOTTOM_LEFT );
lv_obj_clear_flag( cui_StatusPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(cui_StatusPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(cui_StatusPanel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_sbbackground);
ui_object_set_themeable_style_property(cui_StatusPanel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_sbbackground);
lv_obj_set_style_border_color(cui_StatusPanel, lv_color_hex(0x44B8D5), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(cui_StatusPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(cui_StatusPanel, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(cui_StatusPanel, LV_BORDER_SIDE_TOP, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_StatusPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_StatusPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_StatusPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_StatusPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(cui_StatusPanel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_nearwhite);
ui_object_set_themeable_style_property(cui_StatusPanel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_nearwhite);
lv_obj_set_style_text_font(cui_StatusPanel, &ui_font_OswaldRegular20p4, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_TempStatus;
cui_TempStatus = lv_label_create(cui_StatusPanel);
lv_obj_set_width( cui_TempStatus, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_TempStatus, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_TempStatus, 0 );
lv_obj_set_y( cui_TempStatus, 1 );
lv_obj_set_align( cui_TempStatus, LV_ALIGN_CENTER );
lv_label_set_text(cui_TempStatus,"27.0C");

lv_obj_t *cui_TimeStatus;
cui_TimeStatus = lv_label_create(cui_StatusPanel);
lv_obj_set_width( cui_TimeStatus, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_TimeStatus, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_TimeStatus, 3 );
lv_obj_set_y( cui_TimeStatus, 1 );
lv_obj_set_align( cui_TimeStatus, LV_ALIGN_LEFT_MID );
lv_label_set_text(cui_TimeStatus,"00:00");

lv_obj_t *cui_RightFlexPanel;
cui_RightFlexPanel = lv_obj_create(cui_StatusPanel);
lv_obj_set_width( cui_RightFlexPanel, lv_pct(40));
lv_obj_set_height( cui_RightFlexPanel, lv_pct(100));
lv_obj_set_align( cui_RightFlexPanel, LV_ALIGN_RIGHT_MID );
lv_obj_set_flex_flow(cui_RightFlexPanel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(cui_RightFlexPanel, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( cui_RightFlexPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(cui_RightFlexPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(cui_RightFlexPanel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_sbbackground);
ui_object_set_themeable_style_property(cui_RightFlexPanel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_sbbackground);
lv_obj_set_style_border_width(cui_RightFlexPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(cui_RightFlexPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_RightFlexPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_RightFlexPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_RightFlexPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_RightFlexPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(cui_RightFlexPanel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_nearwhite);
ui_object_set_themeable_style_property(cui_RightFlexPanel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_nearwhite);

lv_obj_t *cui_NavStatus;
cui_NavStatus = lv_label_create(cui_RightFlexPanel);
lv_obj_set_width( cui_NavStatus, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_NavStatus, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_NavStatus, 3 );
lv_obj_set_y( cui_NavStatus, 1 );
lv_obj_set_align( cui_NavStatus, LV_ALIGN_LEFT_MID );
lv_label_set_text(cui_NavStatus,"sd");

lv_obj_t *cui_SdStatus;
cui_SdStatus = lv_label_create(cui_RightFlexPanel);
lv_obj_set_width( cui_SdStatus, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_SdStatus, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_SdStatus, 3 );
lv_obj_set_y( cui_SdStatus, 1 );
lv_obj_set_align( cui_SdStatus, LV_ALIGN_LEFT_MID );
lv_label_set_text(cui_SdStatus,"sd");

lv_obj_t *cui_BatStatus;
cui_BatStatus = lv_label_create(cui_RightFlexPanel);
lv_obj_set_width( cui_BatStatus, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_BatStatus, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_BatStatus, 3 );
lv_obj_set_y( cui_BatStatus, 1 );
lv_obj_set_align( cui_BatStatus, LV_ALIGN_RIGHT_MID );
lv_label_set_text(cui_BatStatus,"100%");

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_STATUSPANEL_NUM);
children[UI_COMP_STATUSPANEL_STATUSPANEL] = cui_StatusPanel;
children[UI_COMP_STATUSPANEL_TEMPSTATUS] = cui_TempStatus;
children[UI_COMP_STATUSPANEL_TIMESTATUS] = cui_TimeStatus;
children[UI_COMP_STATUSPANEL_RIGHTFLEXPANEL] = cui_RightFlexPanel;
children[UI_COMP_STATUSPANEL_RIGHTFLEXPANEL_NAVSTATUS] = cui_NavStatus;
children[UI_COMP_STATUSPANEL_RIGHTFLEXPANEL_SDSTATUS] = cui_SdStatus;
children[UI_COMP_STATUSPANEL_RIGHTFLEXPANEL_BATSTATUS] = cui_BatStatus;
lv_obj_add_event_cb(cui_StatusPanel, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_StatusPanel, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_StatusPanel_create_hook(cui_StatusPanel);
return cui_StatusPanel; 
}

