// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: squareline_proj_2_13_01

#include "../ui.h"


// COMPONENT StatusPanel

lv_obj_t * ui_StatusPanel_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_StatusPanel;
    cui_StatusPanel = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_StatusPanel, lv_pct(100));
    lv_obj_set_height(cui_StatusPanel, lv_pct(100));
    lv_obj_set_align(cui_StatusPanel, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(cui_StatusPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(cui_StatusPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_StatusPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_StatusPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_StatusPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_StatusPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_StatusPanel, &ui_font_OswaldRegular16p4, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_BatLabel;
    cui_BatLabel = lv_label_create(cui_StatusPanel);
    lv_obj_set_width(cui_BatLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_BatLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_BatLabel, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(cui_BatLabel, "100%");

    lv_obj_t * cui_TempLabel;
    cui_TempLabel = lv_label_create(cui_StatusPanel);
    lv_obj_set_width(cui_TempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_TempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_TempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(cui_TempLabel, "25.5C");

    lv_obj_t * cui_TimeLabel;
    cui_TimeLabel = lv_label_create(cui_StatusPanel);
    lv_obj_set_width(cui_TimeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_TimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_TimeLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_TimeLabel, "19:01");

    lv_obj_t * cui_SDImage;
    cui_SDImage = lv_img_create(cui_StatusPanel);
    lv_img_set_src(cui_SDImage, &ui_img_sd_card_fill0_wght400_grad0_opsz24_png);
    lv_obj_set_width(cui_SDImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_SDImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_SDImage, -42);
    lv_obj_set_y(cui_SDImage, 0);
    lv_obj_set_align(cui_SDImage, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(cui_SDImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_SDImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(cui_SDImage, 255);

    lv_obj_t * cui_NavImage;
    cui_NavImage = lv_img_create(cui_StatusPanel);
    lv_img_set_src(cui_NavImage, &ui_img_wifi_fill0_wght400_grad0_opsz24_png);
    lv_obj_set_width(cui_NavImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_NavImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_NavImage, -65);
    lv_obj_set_y(cui_NavImage, 0);
    lv_obj_set_align(cui_NavImage, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(cui_NavImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_NavImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(cui_NavImage, 255);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_STATUSPANEL_NUM);
    children[UI_COMP_STATUSPANEL_STATUSPANEL] = cui_StatusPanel;
    children[UI_COMP_STATUSPANEL_BATLABEL] = cui_BatLabel;
    children[UI_COMP_STATUSPANEL_TEMPLABEL] = cui_TempLabel;
    children[UI_COMP_STATUSPANEL_TIMELABEL] = cui_TimeLabel;
    children[UI_COMP_STATUSPANEL_SDIMAGE] = cui_SDImage;
    children[UI_COMP_STATUSPANEL_NAVIMAGE] = cui_NavImage;
    lv_obj_add_event_cb(cui_StatusPanel, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_StatusPanel, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_StatusPanel_create_hook(cui_StatusPanel);
    return cui_StatusPanel;
}

