// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: squareline_proj_2_13_01_status

#include "../ui.h"


// COMPONENT StatusPanel

lv_obj_t *ui_StatusPanel_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_StatusPanel;
cui_StatusPanel = lv_obj_create(comp_parent);
lv_obj_set_width( cui_StatusPanel, lv_pct(100));
lv_obj_set_height( cui_StatusPanel, lv_pct(100));
lv_obj_set_align( cui_StatusPanel, LV_ALIGN_BOTTOM_LEFT );
lv_obj_clear_flag( cui_StatusPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(cui_StatusPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(cui_StatusPanel, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(cui_StatusPanel, LV_BORDER_SIDE_TOP, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_StatusPanel, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_StatusPanel, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_StatusPanel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_StatusPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_pad_left(cui_StatusPanel, 3, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_StatusPanel, 3, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_StatusPanel, 2, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_StatusPanel, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

lv_obj_t *cui_RightCnt;
cui_RightCnt = lv_obj_create(cui_StatusPanel);
lv_obj_remove_style_all(cui_RightCnt);
lv_obj_set_width( cui_RightCnt, lv_pct(65));
lv_obj_set_height( cui_RightCnt, lv_pct(100));
lv_obj_set_align( cui_RightCnt, LV_ALIGN_TOP_RIGHT );
lv_obj_set_flex_flow(cui_RightCnt,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(cui_RightCnt, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( cui_RightCnt, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_t *cui_tempStat;
cui_tempStat = lv_label_create(cui_RightCnt);
lv_obj_set_width( cui_tempStat, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_tempStat, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_tempStat, LV_ALIGN_LEFT_MID );
lv_label_set_text(cui_tempStat,"25.5C");
lv_obj_set_style_pad_left(cui_tempStat, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_tempStat, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_tempStat, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_tempStat, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_navImg;
cui_navImg = lv_label_create(cui_RightCnt);
lv_obj_set_width( cui_navImg, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_navImg, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_navImg, LV_ALIGN_LEFT_MID );
lv_label_set_text(cui_navImg,"nav");
lv_obj_set_style_pad_left(cui_navImg, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_navImg, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_navImg, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_navImg, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_sdImg;
cui_sdImg = lv_label_create(cui_RightCnt);
lv_obj_set_width( cui_sdImg, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_sdImg, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_sdImg, LV_ALIGN_LEFT_MID );
lv_label_set_text(cui_sdImg,"sd");
lv_obj_set_style_pad_left(cui_sdImg, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_sdImg, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_sdImg, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_sdImg, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_batImg;
cui_batImg = lv_label_create(cui_RightCnt);
lv_obj_set_width( cui_batImg, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_batImg, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_batImg, LV_ALIGN_RIGHT_MID );
lv_label_set_text(cui_batImg,"bat");
lv_obj_set_style_pad_left(cui_batImg, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_batImg, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_batImg, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_batImg, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_batStat;
cui_batStat = lv_label_create(cui_RightCnt);
lv_obj_set_width( cui_batStat, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_batStat, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_batStat, LV_ALIGN_RIGHT_MID );
lv_label_set_text(cui_batStat,"100%");
lv_obj_set_style_pad_left(cui_batStat, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_batStat, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_batStat, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_batStat, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_LeftCnt;
cui_LeftCnt = lv_obj_create(cui_StatusPanel);
lv_obj_remove_style_all(cui_LeftCnt);
lv_obj_set_width( cui_LeftCnt, lv_pct(24));
lv_obj_set_height( cui_LeftCnt, lv_pct(100));
lv_obj_set_flex_flow(cui_LeftCnt,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(cui_LeftCnt, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( cui_LeftCnt, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_t *cui_timeStat;
cui_timeStat = lv_label_create(cui_LeftCnt);
lv_obj_set_width( cui_timeStat, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_timeStat, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_timeStat, LV_ALIGN_LEFT_MID );
lv_label_set_text(cui_timeStat,"00:00");

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_STATUSPANEL_NUM);
children[UI_COMP_STATUSPANEL_STATUSPANEL] = cui_StatusPanel;
children[UI_COMP_STATUSPANEL_RIGHTCNT] = cui_RightCnt;
children[UI_COMP_STATUSPANEL_RIGHTCNT_TEMPSTAT] = cui_tempStat;
children[UI_COMP_STATUSPANEL_RIGHTCNT_NAVIMG] = cui_navImg;
children[UI_COMP_STATUSPANEL_RIGHTCNT_SDIMG] = cui_sdImg;
children[UI_COMP_STATUSPANEL_RIGHTCNT_BATIMG] = cui_batImg;
children[UI_COMP_STATUSPANEL_RIGHTCNT_BATSTAT] = cui_batStat;
children[UI_COMP_STATUSPANEL_LEFTCNT] = cui_LeftCnt;
children[UI_COMP_STATUSPANEL_LEFTCNT_TIMESTAT] = cui_timeStat;
lv_obj_add_event_cb(cui_StatusPanel, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_StatusPanel, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_StatusPanel_create_hook(cui_StatusPanel);
return cui_StatusPanel; 
}

