// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: squareline_proj_2_13_01

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_SpeedScreen
void ui_SpeedScreen_screen_init(void);
lv_obj_t *ui_SpeedScreen = 0;


// SCREEN: ui_InfoScreen
void ui_InfoScreen_screen_init(void);
lv_obj_t *ui_InfoScreen = 0;

// SCREEN: ui_InitScreen
void ui_InitScreen_screen_init(void);
lv_obj_t *ui_InitScreen = 0;


// SCREEN: ui_StatsScreen
void ui_StatsScreen_screen_init(int rows, int cols);
lv_obj_t *ui_StatsScreen = 0;

// SCREEN: ui_SleepScreen
void ui_SleepScreen_screen_init(void);
lv_obj_t *ui_SleepScreen = 0;

lv_obj_t *ui____initial_actions0;

void ui_init( void )
{
    ui_common_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    // lv_disp_load_scr( ui_SpeedScreen);
}

void ui_deinit() {
    if(ui____initial_actions0)
        lv_obj_del(ui____initial_actions0);
    ui_common_deinit();
}

#if defined(USE_2BPP_FONT)
const lv_font_t * ui_status_font_default = &ui_font_OswaldRegular20p2;
#else
const lv_font_t * ui_status_font_default = &ui_font_OswaldRegular20p4;
#endif

void ui_StatusPanel_init(ui_screen_t *parent) {
    if (ui_StatusPanel != NULL)
        return;
#if defined(STATUS_PANEL_V1)
    ui_StatusPanel = ui_StatusPanel_create_B(parent->status_cnt);
#else
    ui_StatusPanel = lv_statusbar_create(parent->status_cnt);
#endif
    lv_obj_set_x(ui_StatusPanel, 0);
    lv_obj_set_y(ui_StatusPanel, 0);
    lv_obj_set_style_bg_color(ui_StatusPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StatusPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StatusPanel, lv_color_hex(0x0D0D0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StatusPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_StatusPanel, lv_color_hex(0x0D0D0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StatusPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StatusPanel, parent->status_font ? parent->status_font : ui_status_font_default, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void loadSleepScreen() {
    if (ui_SleepScreen == 0) {
#if defined(USE_2BPP_FONT)
        ui_sleep_screen.font.normal = &ui_font_OpenSansSemiBold16p2;
        ui_sleep_screen.font.title = &ui_font_SFDistantGalaxyRegular16p2;
        ui_sleep_screen.screen.status_font = &ui_font_OswaldRegular14p2;
#else
        ui_sleep_screen.font.normal = &ui_font_OpenSansSemiBold16p4;
        ui_sleep_screen.font.title = &ui_font_SFDistantGalaxyRegular16p4;
        ui_sleep_screen.screen.status_font = &ui_font_OswaldRegular14p4;
#endif
    }
    ui_SleepScreen_screen_init();
    if(lv_disp_get_scr_act(lv_disp_get_default()) != ui_SleepScreen){
        #if defined(STATUS_PANEL_V1)
        ui_StatusPanel_load(&ui_sleep_screen.screen, 1);
        #else
        ui_StatusPanel_load(&ui_sleep_screen.screen, 1);
        #endif
        lv_scr_load(ui_SleepScreen);
    }
}

void loadInfoScreen() {
    if (ui_InfoScreen == 0) {
#if defined(USE_2BPP_FONT)
        ui_info_screen.font.title = &ui_font_OswaldRegular24p2;
        ui_info_screen.font.info = &ui_font_OswaldRegular16p2;
#else
        ui_info_screen.font.title = &ui_font_OswaldRegular24p4;
        ui_info_screen.font.info = &ui_font_OswaldRegular16p4;
#endif
    }
    ui_InfoScreen_screen_init();
    if(lv_disp_get_scr_act(lv_disp_get_default()) != ui_InfoScreen){
        #if defined(STATUS_PANEL_V1)
        ui_StatusPanel_load(&ui_info_screen.screen, 0);
        #else
        ui_StatusPanel_load(&ui_info_screen.screen, 0);
        #endif
        lv_scr_load(ui_InfoScreen);
    }
}

void loadInitScreen() {
    if (ui_InitScreen == 0) {
#if defined(USE_2BPP_FONT)
        ui_init_screen.font.title = &ui_font_OswaldRegular24p2;
#else
        ui_init_screen.font.title = &ui_font_OswaldRegular24p4;
#endif
    }
    ui_InitScreen_screen_init();
    if(lv_disp_get_scr_act(lv_disp_get_default()) != ui_InitScreen){
        lv_scr_load(ui_InitScreen);
    }
}

void loadSpeedScreen() {
    if (ui_SpeedScreen == 0) {
#if defined(USE_2BPP_FONT)
        ui_speed_screen.font.main = &ui_font_OpenSansBold84p2;
        ui_speed_screen.font.title = &ui_font_OpenSansBold36p2;
        ui_speed_screen.font.info = &ui_font_OswaldRegular16p2;
        ui_speed_screen.screen.status_font = &ui_font_OswaldRegular14p2;
#else
        ui_speed_screen.font.main = &ui_font_OpenSansBold84p4;
        ui_speed_screen.font.title = &ui_font_OpenSansBold36p4;
        ui_speed_screen.font.info = &ui_font_OswaldRegular16p4;
        ui_speed_screen.screen.status_font = &ui_font_OswaldRegular14p4;
#endif
    }
    ui_SpeedScreen_screen_init();
    if(lv_disp_get_scr_act(lv_disp_get_default()) != ui_SpeedScreen){
        #if defined(STATUS_PANEL_V1)
        ui_StatusPanel_load(&ui_speed_screen.screen, 2);
        #else
        ui_StatusPanel_load(&ui_speed_screen.screen, 2);
        #endif
        lv_scr_load(ui_SpeedScreen);
    }
}

void loadStatsScreen(int rows, int cols) {
    if (ui_StatsScreen == 0) {
#if defined(USE_2BPP_FONT)
        ui_stats_screen.font.title = &ui_font_OpenSansBold28p2;
        ui_stats_screen.font.title_big = &ui_font_OpenSansBold60p2;
        ui_stats_screen.font.info = &ui_font_OswaldRegular16p2;
#else
        ui_stats_screen.font.title = &ui_font_OpenSansBold28p4;
        ui_stats_screen.font.title_big = &ui_font_OpenSansBold60p4;
        ui_stats_screen.font.info = &ui_font_OswaldRegular16p4;
#endif
    }
    ui_StatsScreen_screen_init(rows, cols);
    if(lv_disp_get_scr_act(lv_disp_get_default()) != ui_StatsScreen){
        #if defined(STATUS_PANEL_V1)
        ui_StatusPanel_load(&ui_stats_screen.screen, 0);
        #else
        ui_StatusPanel_load(&ui_stats_screen.screen, 0);

        #endif
        lv_scr_load(ui_StatsScreen);
    }
}
