// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: squareline_proj_2_13_01

#include "ui.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_SpeedScreen
lv_obj_t * ui_SpeedBar;
lv_obj_t * ui_SpeedMainPanelWrapper;
lv_obj_t * ui_SpeedMainPanel;
lv_obj_t * ui_SpeedSecondaryPanel;
lv_obj_t * ui_LeftPanel;
lv_obj_t * ui_RightPanel;
lv_obj_t * ui_SpeedStatusPanelWrapper;
lv_obj_t * ui_SpeedStatusPanel;


// SCREEN: ui_InfoScreen
lv_obj_t * ui_InfoStatusPanelWrapper;
lv_obj_t * ui_InfoStatusPanel;
lv_obj_t * ui_InfoMainPanel;
lv_obj_t * ui_MainImage;
lv_obj_t * ui_MainLabel;
lv_obj_t * ui_MainLowerLabel;
lv_obj_t * ui_InfoInitPanel;
lv_obj_t * ui_InitImage;
lv_obj_t * ui_InitLabel;


// SCREEN: ui_StatsScreen
lv_obj_t * ui_StatsStatusPanelWrapper;
lv_obj_t * ui_StatsStatusPanel;
lv_obj_t * ui_StatsPanel2Row;
lv_obj_t * ui_StatsPanel2Row1;
lv_obj_t * ui_StatsPanel2Row11;
lv_obj_t * ui_StatsPanel2Row2;
lv_obj_t * ui_StatsPanel2Row2Left;
lv_obj_t * ui_StatsPanel2Row2Right;
lv_obj_t * ui_StatsPanel3Row;
lv_obj_t * ui_StatsPanel3Row1;
lv_obj_t * ui_StatsPanel3Row1Left;
lv_obj_t * ui_StatsPanel3Row1Right;
lv_obj_t * ui_StatsPanel3Row2;
lv_obj_t * ui_StatsPanel3Row2Left;
lv_obj_t * ui_StatsPanel3Row2Right;
lv_obj_t * ui_StatsPanel3Row3;
lv_obj_t * ui_StatsPanel3Row3Left;
lv_obj_t * ui_StatsPanel3Row3Right;
lv_obj_t * ui_StatsPanel4Row;
lv_obj_t * ui_StatsPanel4Row1;
lv_obj_t * ui_StatsPanel4Row1Left;
lv_obj_t * ui_StatsPanel4Row1Right;
lv_obj_t * ui_StatsPanel4Row2;
lv_obj_t * ui_StatsPanel4Row2Left;
lv_obj_t * ui_StatsPanel4Row2Right;
lv_obj_t * ui_StatsPanel4Row3;
lv_obj_t * ui_StatsPanel4Row3Left;
lv_obj_t * ui_StatsPanel4Row3Right;
lv_obj_t * ui_StatsPanel4Row4;
lv_obj_t * ui_StatsPanel4Row4Left;
lv_obj_t * ui_StatsPanel4Row4Right;
const lv_img_dsc_t * ui_imgset_battery_horiz_000_fill0_wght400_grad0_opsz[1] = {&ui_img_battery_horiz_000_fill0_wght400_grad0_opsz24_png};
const lv_img_dsc_t * ui_imgset_navigation_fill0_wght400_grad0_opsz[1] = {&ui_img_navigation_fill0_wght400_grad0_opsz24_png};
const lv_img_dsc_t * ui_imgset_radio_button_checked_fill0_wght400_grad0_opsz[1] = {&ui_img_radio_button_checked_fill0_wght400_grad0_opsz24_png};
const lv_img_dsc_t * ui_imgset_radio_button_partial_fill0_wght400_grad0_opsz[1] = {&ui_img_radio_button_partial_fill0_wght400_grad0_opsz24_png};
const lv_img_dsc_t * ui_imgset_radio_button_unchecked_fill0_wght400_grad0_opsz[1] = {&ui_img_radio_button_unchecked_fill0_wght400_grad0_opsz24_png};
const lv_img_dsc_t * ui_imgset_sd_card_fill0_wght400_grad0_opsz[1] = {&ui_img_sd_card_fill0_wght400_grad0_opsz24_png};
const lv_img_dsc_t * ui_imgset_wifi_fill0_wght400_grad0_opsz[1] = {&ui_img_wifi_fill0_wght400_grad0_opsz24_png};

