// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: squareline_proj_2_13_01

#ifndef A657D16B_6490_49B7_9AB8_3CE81FA306DF
#define A657D16B_6490_49B7_9AB8_3CE81FA306DF

#ifdef __cplusplus
extern "C" {
#endif

#include "ui_common.h"

extern lv_obj_t *ui____initial_actions0;

void ui_init(void);
void ui_deinit();

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif /* A657D16B_6490_49B7_9AB8_3CE81FA306DF */
