// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: squareline_proj_1_54_02

#include "ui_common.h"


// COMPONENT SmallDataPanel

lv_obj_t *ui_SmallDataPanel_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_SmallDataPanel;
cui_SmallDataPanel = lv_obj_create(comp_parent);
lv_obj_set_width( cui_SmallDataPanel, lv_pct(50));
lv_obj_set_height( cui_SmallDataPanel, lv_pct(100));
lv_obj_set_x( cui_SmallDataPanel, 50 );
lv_obj_set_y( cui_SmallDataPanel, 0 );
lv_obj_clear_flag( cui_SmallDataPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(cui_SmallDataPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(cui_SmallDataPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(cui_SmallDataPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_SmallDataPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_SmallDataPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_SmallDataPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_SmallDataPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_border_width(cui_SmallDataPanel, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(cui_SmallDataPanel, LV_BORDER_SIDE_NONE, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

lv_obj_t *cui_DataLabel;
cui_DataLabel = lv_label_create(cui_SmallDataPanel);
lv_obj_set_width( cui_DataLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_DataLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_y( cui_DataLabel, 0 );
lv_obj_set_x( cui_DataLabel, lv_pct(12) );
lv_obj_set_align( cui_DataLabel, LV_ALIGN_CENTER );
lv_label_set_text(cui_DataLabel,"129.09");

lv_obj_t *cui_InfoLabel;
cui_InfoLabel = lv_label_create(cui_SmallDataPanel);
lv_obj_set_width( cui_InfoLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_InfoLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_InfoLabel, 1 );
lv_obj_set_y( cui_InfoLabel, 3 );
lv_obj_set_align( cui_InfoLabel, LV_ALIGN_LEFT_MID );
lv_label_set_text(cui_InfoLabel,"AVG");

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_SMALLDATAPANEL_NUM);
children[UI_COMP_SMALLDATAPANEL_SMALLDATAPANEL] = cui_SmallDataPanel;
children[UI_COMP_SMALLDATAPANEL_DATALABEL] = cui_DataLabel;
children[UI_COMP_SMALLDATAPANEL_INFOLABEL] = cui_InfoLabel;
lv_obj_add_event_cb(cui_SmallDataPanel, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_SmallDataPanel, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_SmallDataPanel_create_hook(cui_SmallDataPanel);
return cui_SmallDataPanel; 
}

