// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: squareline_proj_2_13_01_status

#ifndef _UI_COMP_STATUSPANEL_H
#define _UI_COMP_STATUSPANEL_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT StatusPanel
#define UI_COMP_STATUSPANEL_STATUSPANEL 0
#define UI_COMP_STATUSPANEL_RIGHTCNT 1
#define UI_COMP_STATUSPANEL_RIGHTCNT_TEMPSTAT 2
#define UI_COMP_STATUSPANEL_RIGHTCNT_NAVIMG 3
#define UI_COMP_STATUSPANEL_RIGHTCNT_SDIMG 4
#define UI_COMP_STATUSPANEL_RIGHTCNT_BATIMG 5
#define UI_COMP_STATUSPANEL_RIGHTCNT_BATSTAT 6
#define UI_COMP_STATUSPANEL_LEFTCNT 7
#define UI_COMP_STATUSPANEL_LEFTCNT_TIMESTAT 8
#define _UI_COMP_STATUSPANEL_NUM 9
lv_obj_t *ui_StatusPanel_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
