// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: lilygo_tdisplay_s3_04

#ifndef BCD643FC_8D34_478F_985D_91939BDEC7A9
#define BCD643FC_8D34_478F_985D_91939BDEC7A9

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

void get_component_child_event_cb(lv_event_t * e);
void del_component_child_event_cb(lv_event_t * e);

lv_obj_t * ui_comp_get_child(lv_obj_t * comp, uint32_t child_idx);
extern uint32_t LV_EVENT_GET_COMP_CHILD;
#include "ui_comp_bigdatapanel.h"
#include "ui_comp_smalldatapanel.h"
#include "ui_comp_statuspanel.h"

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif /* BCD643FC_8D34_478F_985D_91939BDEC7A9 */
