// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: lilygo_tdisplay_s3_04

#ifndef F014E056_E64D_4798_80A5_98CFA444EBF6
#define F014E056_E64D_4798_80A5_98CFA444EBF6

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT BigDataPanel
#define UI_COMP_BIGDATAPANEL_BIGDATAPANEL 0
#define UI_COMP_BIGDATAPANEL_INFOLABEL 1
#define UI_COMP_BIGDATAPANEL_DATALABEL 2
#define _UI_COMP_BIGDATAPANEL_NUM 3
lv_obj_t * ui_BigDataPanel_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif /* F014E056_E64D_4798_80A5_98CFA444EBF6 */
