// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: lilygo_tdisplay_s3_04

#ifndef A008117E_6933_45DD_8778_3AA4BEE315AA
#define A008117E_6933_45DD_8778_3AA4BEE315AA

#include <lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_BigDataPanel_create_hook(lv_obj_t * comp);
void ui_comp_SmallDataPanel_create_hook(lv_obj_t * comp);
void ui_comp_StatusPanel_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif /* A008117E_6933_45DD_8778_3AA4BEE315AA */
