// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: lilygo_tdisplay_s3_04

#ifndef EEA1CF63_BE7B_40A6_B68B_BAA44F547FFF
#define EEA1CF63_BE7B_40A6_B68B_BAA44F547FFF

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT SmallDataPanel
#define UI_COMP_SMALLDATAPANEL_SMALLDATAPANEL 0
#define UI_COMP_SMALLDATAPANEL_INFOLABEL 1
#define UI_COMP_SMALLDATAPANEL_DATALABEL 2
#define _UI_COMP_SMALLDATAPANEL_NUM 3
lv_obj_t * ui_SmallDataPanel_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif /* EEA1CF63_BE7B_40A6_B68B_BAA44F547FFF */
