// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: squareline_proj_2_13_01

#include "../ui.h"

void ui_SpeedScreen_screen_init(void)
{
    ui_SpeedScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SpeedScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_SpeedScreen, &ui_font_OswaldRegular16p4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedBar = lv_bar_create(ui_SpeedScreen);
    lv_bar_set_value(ui_SpeedBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_SpeedBar, 0, LV_ANIM_OFF);
    lv_obj_set_height(ui_SpeedBar, 5);
    lv_obj_set_width(ui_SpeedBar, lv_pct(100));
    lv_obj_set_x(ui_SpeedBar, 0);
    lv_obj_set_y(ui_SpeedBar, 42);
    lv_obj_set_style_radius(ui_SpeedBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SpeedBar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeedBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SpeedBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SpeedBar, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeedBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_SpeedMainPanelWrapper = lv_obj_create(ui_SpeedScreen);
    lv_obj_set_width(ui_SpeedMainPanelWrapper, lv_pct(100));
    lv_obj_set_height(ui_SpeedMainPanelWrapper, lv_pct(60));
    lv_obj_set_align(ui_SpeedMainPanelWrapper, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_SpeedMainPanelWrapper, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SpeedMainPanelWrapper, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SpeedMainPanelWrapper, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_SpeedMainPanelWrapper, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SpeedMainPanelWrapper, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SpeedMainPanelWrapper, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SpeedMainPanelWrapper, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SpeedMainPanelWrapper, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedMainPanel = ui_BigDataPanel_create(ui_SpeedMainPanelWrapper);
    lv_obj_set_x(ui_SpeedMainPanel, 0);
    lv_obj_set_y(ui_SpeedMainPanel, 0);

    lv_obj_set_style_text_font(ui_comp_get_child(ui_SpeedMainPanel, UI_COMP_BIGDATAPANEL_DATALABEL),
                               &ui_font_OpenSansBold78p4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedSecondaryPanel = lv_obj_create(ui_SpeedScreen);
    lv_obj_set_width(ui_SpeedSecondaryPanel, lv_pct(100));
    lv_obj_set_height(ui_SpeedSecondaryPanel, lv_pct(35));
    lv_obj_clear_flag(ui_SpeedSecondaryPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_SpeedSecondaryPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_SpeedSecondaryPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SpeedSecondaryPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SpeedSecondaryPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SpeedSecondaryPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SpeedSecondaryPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LeftPanel = ui_SmallDataPanel_create(ui_SpeedSecondaryPanel);
    lv_obj_set_x(ui_LeftPanel, 0);
    lv_obj_set_y(ui_LeftPanel, 1);

    lv_obj_set_style_text_font(ui_comp_get_child(ui_LeftPanel, UI_COMP_SMALLDATAPANEL_DATALABEL), &ui_font_OpenSansBold30p4,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RightPanel = ui_SmallDataPanel_create(ui_SpeedSecondaryPanel);
    lv_obj_set_x(ui_RightPanel, 125);
    lv_obj_set_y(ui_RightPanel, 1);

    lv_obj_set_style_text_font(ui_comp_get_child(ui_RightPanel, UI_COMP_SMALLDATAPANEL_DATALABEL),
                               &ui_font_OpenSansBold30p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedStatusPanelWrapper = lv_obj_create(ui_SpeedScreen);
    lv_obj_set_width(ui_SpeedStatusPanelWrapper, lv_pct(100));
    lv_obj_set_height(ui_SpeedStatusPanelWrapper, lv_pct(17));
    lv_obj_set_align(ui_SpeedStatusPanelWrapper, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_SpeedStatusPanelWrapper, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_SpeedStatusPanelWrapper, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_SpeedStatusPanelWrapper, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_SpeedStatusPanelWrapper, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SpeedStatusPanelWrapper, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SpeedStatusPanelWrapper, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SpeedStatusPanelWrapper, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SpeedStatusPanelWrapper, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedStatusPanel = ui_StatusPanel_create(ui_SpeedStatusPanelWrapper);
    lv_obj_set_x(ui_SpeedStatusPanel, 0);
    lv_obj_set_y(ui_SpeedStatusPanel, 0);





}
