// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: squareline_proj_2_13_01

#include "../ui.h"

void ui_StatsScreen_screen_init(void)
{
    ui_StatsScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_StatsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_StatsStatusPanelWrapper = lv_obj_create(ui_StatsScreen);
    lv_obj_set_width(ui_StatsStatusPanelWrapper, lv_pct(100));
    lv_obj_set_height(ui_StatsStatusPanelWrapper, lv_pct(17));
    lv_obj_set_align(ui_StatsStatusPanelWrapper, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_StatsStatusPanelWrapper, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_StatsStatusPanelWrapper, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsStatusPanelWrapper, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_StatsStatusPanelWrapper, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_StatsStatusPanelWrapper, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_StatsStatusPanelWrapper, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_StatsStatusPanelWrapper, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsStatusPanel = ui_StatusPanel_create(ui_StatsStatusPanelWrapper);
    lv_obj_set_x(ui_StatsStatusPanel, 0);
    lv_obj_set_y(ui_StatsStatusPanel, 0);





    ui_StatsPanel2Row = lv_obj_create(ui_StatsScreen);
    lv_obj_set_width(ui_StatsPanel2Row, lv_pct(100));
    lv_obj_set_height(ui_StatsPanel2Row, lv_pct(82));
    lv_obj_add_flag(ui_StatsPanel2Row, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_StatsPanel2Row, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StatsPanel2Row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel2Row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsPanel2Row, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_StatsPanel2Row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_StatsPanel2Row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_StatsPanel2Row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_StatsPanel2Row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel2Row1 = lv_obj_create(ui_StatsPanel2Row);
    lv_obj_set_width(ui_StatsPanel2Row1, lv_pct(100));
    lv_obj_set_height(ui_StatsPanel2Row1, lv_pct(66));
    lv_obj_clear_flag(ui_StatsPanel2Row1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StatsPanel2Row1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StatsPanel2Row1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StatsPanel2Row1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel2Row1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsPanel2Row1, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_StatsPanel2Row1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_StatsPanel2Row1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_StatsPanel2Row1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_StatsPanel2Row1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StatsPanel2Row1, &ui_font_OswaldRegular16p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel2Row11 = ui_BigDataPanel_create(ui_StatsPanel2Row1);
    lv_obj_set_x(ui_StatsPanel2Row11, 0);
    lv_obj_set_y(ui_StatsPanel2Row11, 0);

    lv_obj_set_style_text_font(ui_comp_get_child(ui_StatsPanel2Row11, UI_COMP_BIGDATAPANEL_DATALABEL),
                               &ui_font_OpenSansBold60p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_x(ui_comp_get_child(ui_StatsPanel2Row11, UI_COMP_BIGDATAPANEL_INFOLABEL), lv_pct(1));
    lv_obj_set_y(ui_comp_get_child(ui_StatsPanel2Row11, UI_COMP_BIGDATAPANEL_INFOLABEL), lv_pct(-9));
    lv_obj_clear_flag(ui_comp_get_child(ui_StatsPanel2Row11, UI_COMP_BIGDATAPANEL_INFOLABEL),
                      LV_OBJ_FLAG_HIDDEN);      /// Flags

    ui_StatsPanel2Row2 = lv_obj_create(ui_StatsPanel2Row);
    lv_obj_set_width(ui_StatsPanel2Row2, lv_pct(100));
    lv_obj_set_height(ui_StatsPanel2Row2, lv_pct(33));
    lv_obj_set_x(ui_StatsPanel2Row2, 0);
    lv_obj_set_y(ui_StatsPanel2Row2, lv_pct(66));
    lv_obj_clear_flag(ui_StatsPanel2Row2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StatsPanel2Row2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StatsPanel2Row2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StatsPanel2Row2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel2Row2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsPanel2Row2, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_StatsPanel2Row2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_StatsPanel2Row2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_StatsPanel2Row2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_StatsPanel2Row2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StatsPanel2Row2, &ui_font_OswaldRegular16p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel2Row2Left = ui_SmallDataPanel_create(ui_StatsPanel2Row2);
    lv_obj_set_width(ui_StatsPanel2Row2Left, lv_pct(50));
    lv_obj_set_height(ui_StatsPanel2Row2Left, lv_pct(100));
    lv_obj_set_x(ui_StatsPanel2Row2Left, 0);
    lv_obj_set_y(ui_StatsPanel2Row2Left, 0);
    lv_obj_set_align(ui_StatsPanel2Row2Left, LV_ALIGN_TOP_LEFT);
    lv_obj_set_style_radius(ui_StatsPanel2Row2Left, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StatsPanel2Row2Left, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StatsPanel2Row2Left, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel2Row2Left, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsPanel2Row2Left, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_x(ui_comp_get_child(ui_StatsPanel2Row2Left, UI_COMP_SMALLDATAPANEL_DATALABEL), 14);
    lv_obj_set_y(ui_comp_get_child(ui_StatsPanel2Row2Left, UI_COMP_SMALLDATAPANEL_DATALABEL), 3);
    lv_obj_set_style_text_font(ui_comp_get_child(ui_StatsPanel2Row2Left, UI_COMP_SMALLDATAPANEL_DATALABEL),
                               &ui_font_OpenSansBold30p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel2Row2Right = ui_SmallDataPanel_create(ui_StatsPanel2Row2);
    lv_obj_set_x(ui_StatsPanel2Row2Right, 125);
    lv_obj_set_y(ui_StatsPanel2Row2Right, 0);

    lv_obj_set_style_text_font(ui_comp_get_child(ui_StatsPanel2Row2Right, UI_COMP_SMALLDATAPANEL_DATALABEL),
                               &ui_font_OpenSansBold30p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel3Row = lv_obj_create(ui_StatsScreen);
    lv_obj_set_width(ui_StatsPanel3Row, lv_pct(100));
    lv_obj_set_height(ui_StatsPanel3Row, lv_pct(82));
    lv_obj_add_flag(ui_StatsPanel3Row, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_StatsPanel3Row, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StatsPanel3Row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel3Row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsPanel3Row, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_StatsPanel3Row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_StatsPanel3Row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_StatsPanel3Row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_StatsPanel3Row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel3Row1 = lv_obj_create(ui_StatsPanel3Row);
    lv_obj_set_width(ui_StatsPanel3Row1, lv_pct(100));
    lv_obj_set_height(ui_StatsPanel3Row1, lv_pct(33));
    lv_obj_clear_flag(ui_StatsPanel3Row1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StatsPanel3Row1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StatsPanel3Row1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StatsPanel3Row1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel3Row1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsPanel3Row1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_StatsPanel3Row1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_StatsPanel3Row1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_StatsPanel3Row1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_StatsPanel3Row1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StatsPanel3Row1, &ui_font_OswaldRegular16p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel3Row1Left = ui_SmallDataPanel_create(ui_StatsPanel3Row1);
    lv_obj_set_width(ui_StatsPanel3Row1Left, lv_pct(50));
    lv_obj_set_height(ui_StatsPanel3Row1Left, lv_pct(100));
    lv_obj_set_x(ui_StatsPanel3Row1Left, 0);
    lv_obj_set_y(ui_StatsPanel3Row1Left, 0);
    lv_obj_set_align(ui_StatsPanel3Row1Left, LV_ALIGN_TOP_LEFT);
    lv_obj_set_style_radius(ui_StatsPanel3Row1Left, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StatsPanel3Row1Left, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StatsPanel3Row1Left, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel3Row1Left, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsPanel3Row1Left, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_x(ui_comp_get_child(ui_StatsPanel3Row1Left, UI_COMP_SMALLDATAPANEL_DATALABEL), 14);
    lv_obj_set_y(ui_comp_get_child(ui_StatsPanel3Row1Left, UI_COMP_SMALLDATAPANEL_DATALABEL), 3);
    lv_obj_set_style_text_font(ui_comp_get_child(ui_StatsPanel3Row1Left, UI_COMP_SMALLDATAPANEL_DATALABEL),
                               &ui_font_OpenSansBold30p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel3Row1Right = ui_SmallDataPanel_create(ui_StatsPanel3Row1);
    lv_obj_set_x(ui_StatsPanel3Row1Right, 125);
    lv_obj_set_y(ui_StatsPanel3Row1Right, 0);

    lv_obj_set_style_text_font(ui_comp_get_child(ui_StatsPanel3Row1Right, UI_COMP_SMALLDATAPANEL_DATALABEL),
                               &ui_font_OpenSansBold30p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel3Row2 = lv_obj_create(ui_StatsPanel3Row);
    lv_obj_set_width(ui_StatsPanel3Row2, lv_pct(100));
    lv_obj_set_height(ui_StatsPanel3Row2, lv_pct(33));
    lv_obj_set_x(ui_StatsPanel3Row2, 0);
    lv_obj_set_y(ui_StatsPanel3Row2, lv_pct(33));
    lv_obj_clear_flag(ui_StatsPanel3Row2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StatsPanel3Row2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StatsPanel3Row2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StatsPanel3Row2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel3Row2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsPanel3Row2, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_StatsPanel3Row2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_StatsPanel3Row2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_StatsPanel3Row2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_StatsPanel3Row2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StatsPanel3Row2, &ui_font_OswaldRegular16p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel3Row2Left = ui_SmallDataPanel_create(ui_StatsPanel3Row2);
    lv_obj_set_x(ui_StatsPanel3Row2Left, 0);
    lv_obj_set_y(ui_StatsPanel3Row2Left, 0);
    lv_obj_set_style_border_color(ui_StatsPanel3Row2Left, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StatsPanel3Row2Left, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel3Row2Left, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsPanel3Row2Left, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_comp_get_child(ui_StatsPanel3Row2Left, UI_COMP_SMALLDATAPANEL_DATALABEL),
                               &ui_font_OpenSansBold30p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel3Row2Right = ui_SmallDataPanel_create(ui_StatsPanel3Row2);
    lv_obj_set_x(ui_StatsPanel3Row2Right, 125);
    lv_obj_set_y(ui_StatsPanel3Row2Right, 0);

    lv_obj_set_style_text_font(ui_comp_get_child(ui_StatsPanel3Row2Right, UI_COMP_SMALLDATAPANEL_DATALABEL),
                               &ui_font_OpenSansBold30p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel3Row3 = lv_obj_create(ui_StatsPanel3Row);
    lv_obj_set_width(ui_StatsPanel3Row3, lv_pct(100));
    lv_obj_set_height(ui_StatsPanel3Row3, lv_pct(33));
    lv_obj_set_x(ui_StatsPanel3Row3, 0);
    lv_obj_set_y(ui_StatsPanel3Row3, lv_pct(66));
    lv_obj_clear_flag(ui_StatsPanel3Row3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StatsPanel3Row3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StatsPanel3Row3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StatsPanel3Row3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel3Row3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsPanel3Row3, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_StatsPanel3Row3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_StatsPanel3Row3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_StatsPanel3Row3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_StatsPanel3Row3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StatsPanel3Row3, &ui_font_OswaldRegular16p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel3Row3Left = ui_SmallDataPanel_create(ui_StatsPanel3Row3);
    lv_obj_set_x(ui_StatsPanel3Row3Left, 0);
    lv_obj_set_y(ui_StatsPanel3Row3Left, 0);
    lv_obj_set_style_border_color(ui_StatsPanel3Row3Left, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StatsPanel3Row3Left, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel3Row3Left, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsPanel3Row3Left, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_comp_get_child(ui_StatsPanel3Row3Left, UI_COMP_SMALLDATAPANEL_DATALABEL),
                               &ui_font_OpenSansBold30p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel3Row3Right = ui_SmallDataPanel_create(ui_StatsPanel3Row3);
    lv_obj_set_x(ui_StatsPanel3Row3Right, 125);
    lv_obj_set_y(ui_StatsPanel3Row3Right, 0);

    lv_obj_set_style_text_font(ui_comp_get_child(ui_StatsPanel3Row3Right, UI_COMP_SMALLDATAPANEL_DATALABEL),
                               &ui_font_OpenSansBold30p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel4Row = lv_obj_create(ui_StatsScreen);
    lv_obj_set_width(ui_StatsPanel4Row, lv_pct(100));
    lv_obj_set_height(ui_StatsPanel4Row, lv_pct(82));
    lv_obj_clear_flag(ui_StatsPanel4Row, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StatsPanel4Row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel4Row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsPanel4Row, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_StatsPanel4Row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_StatsPanel4Row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_StatsPanel4Row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_StatsPanel4Row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel4Row1 = lv_obj_create(ui_StatsPanel4Row);
    lv_obj_set_width(ui_StatsPanel4Row1, lv_pct(100));
    lv_obj_set_height(ui_StatsPanel4Row1, lv_pct(25));
    lv_obj_clear_flag(ui_StatsPanel4Row1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StatsPanel4Row1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StatsPanel4Row1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StatsPanel4Row1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel4Row1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsPanel4Row1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_StatsPanel4Row1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_StatsPanel4Row1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_StatsPanel4Row1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_StatsPanel4Row1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StatsPanel4Row1, &ui_font_OswaldRegular14p4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel4Row1Left = ui_SmallDataPanel_create(ui_StatsPanel4Row1);
    lv_obj_set_width(ui_StatsPanel4Row1Left, lv_pct(50));
    lv_obj_set_height(ui_StatsPanel4Row1Left, lv_pct(100));
    lv_obj_set_x(ui_StatsPanel4Row1Left, 0);
    lv_obj_set_y(ui_StatsPanel4Row1Left, 0);
    lv_obj_set_align(ui_StatsPanel4Row1Left, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_radius(ui_StatsPanel4Row1Left, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StatsPanel4Row1Left, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StatsPanel4Row1Left, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel4Row1Left, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsPanel4Row1Left, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_x(ui_comp_get_child(ui_StatsPanel4Row1Left, UI_COMP_SMALLDATAPANEL_DATALABEL), 14);
    lv_obj_set_y(ui_comp_get_child(ui_StatsPanel4Row1Left, UI_COMP_SMALLDATAPANEL_DATALABEL), 2);
    lv_obj_set_align(ui_comp_get_child(ui_StatsPanel4Row1Left, UI_COMP_SMALLDATAPANEL_DATALABEL), LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_comp_get_child(ui_StatsPanel4Row1Left, UI_COMP_SMALLDATAPANEL_DATALABEL),
                               &ui_font_OpenSansBold24p4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel4Row1Right = ui_SmallDataPanel_create(ui_StatsPanel4Row1);
    lv_obj_set_x(ui_StatsPanel4Row1Right, 125);
    lv_obj_set_y(ui_StatsPanel4Row1Right, 0);

    lv_obj_set_style_text_font(ui_comp_get_child(ui_StatsPanel4Row1Right, UI_COMP_SMALLDATAPANEL_DATALABEL),
                               &ui_font_OpenSansBold24p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel4Row2 = lv_obj_create(ui_StatsPanel4Row);
    lv_obj_set_width(ui_StatsPanel4Row2, lv_pct(100));
    lv_obj_set_height(ui_StatsPanel4Row2, lv_pct(25));
    lv_obj_set_x(ui_StatsPanel4Row2, 0);
    lv_obj_set_y(ui_StatsPanel4Row2, lv_pct(25));
    lv_obj_clear_flag(ui_StatsPanel4Row2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StatsPanel4Row2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StatsPanel4Row2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StatsPanel4Row2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel4Row2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsPanel4Row2, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_StatsPanel4Row2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_StatsPanel4Row2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_StatsPanel4Row2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_StatsPanel4Row2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StatsPanel4Row2, &ui_font_OswaldRegular14p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel4Row2Left = ui_SmallDataPanel_create(ui_StatsPanel4Row2);
    lv_obj_set_x(ui_StatsPanel4Row2Left, 0);
    lv_obj_set_y(ui_StatsPanel4Row2Left, 0);
    lv_obj_set_style_border_color(ui_StatsPanel4Row2Left, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StatsPanel4Row2Left, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel4Row2Left, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsPanel4Row2Left, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_comp_get_child(ui_StatsPanel4Row2Left, UI_COMP_SMALLDATAPANEL_DATALABEL),
                               &ui_font_OpenSansBold24p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel4Row2Right = ui_SmallDataPanel_create(ui_StatsPanel4Row2);
    lv_obj_set_x(ui_StatsPanel4Row2Right, 125);
    lv_obj_set_y(ui_StatsPanel4Row2Right, 0);

    lv_obj_set_style_text_font(ui_comp_get_child(ui_StatsPanel4Row2Right, UI_COMP_SMALLDATAPANEL_DATALABEL),
                               &ui_font_OpenSansBold24p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel4Row3 = lv_obj_create(ui_StatsPanel4Row);
    lv_obj_set_width(ui_StatsPanel4Row3, lv_pct(100));
    lv_obj_set_height(ui_StatsPanel4Row3, lv_pct(25));
    lv_obj_set_x(ui_StatsPanel4Row3, 0);
    lv_obj_set_y(ui_StatsPanel4Row3, lv_pct(50));
    lv_obj_clear_flag(ui_StatsPanel4Row3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StatsPanel4Row3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StatsPanel4Row3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StatsPanel4Row3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel4Row3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsPanel4Row3, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_StatsPanel4Row3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_StatsPanel4Row3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_StatsPanel4Row3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_StatsPanel4Row3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StatsPanel4Row3, &ui_font_OswaldRegular14p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel4Row3Left = ui_SmallDataPanel_create(ui_StatsPanel4Row3);
    lv_obj_set_x(ui_StatsPanel4Row3Left, 0);
    lv_obj_set_y(ui_StatsPanel4Row3Left, 0);
    lv_obj_set_style_border_color(ui_StatsPanel4Row3Left, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StatsPanel4Row3Left, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel4Row3Left, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsPanel4Row3Left, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_comp_get_child(ui_StatsPanel4Row3Left, UI_COMP_SMALLDATAPANEL_DATALABEL),
                               &ui_font_OpenSansBold24p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel4Row3Right = ui_SmallDataPanel_create(ui_StatsPanel4Row3);
    lv_obj_set_x(ui_StatsPanel4Row3Right, 125);
    lv_obj_set_y(ui_StatsPanel4Row3Right, 0);

    lv_obj_set_style_text_font(ui_comp_get_child(ui_StatsPanel4Row3Right, UI_COMP_SMALLDATAPANEL_DATALABEL),
                               &ui_font_OpenSansBold24p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel4Row4 = lv_obj_create(ui_StatsPanel4Row);
    lv_obj_set_width(ui_StatsPanel4Row4, lv_pct(100));
    lv_obj_set_height(ui_StatsPanel4Row4, lv_pct(25));
    lv_obj_set_x(ui_StatsPanel4Row4, 0);
    lv_obj_set_y(ui_StatsPanel4Row4, lv_pct(75));
    lv_obj_clear_flag(ui_StatsPanel4Row4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StatsPanel4Row4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StatsPanel4Row4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StatsPanel4Row4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel4Row4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsPanel4Row4, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_StatsPanel4Row4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_StatsPanel4Row4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_StatsPanel4Row4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_StatsPanel4Row4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StatsPanel4Row4, &ui_font_OswaldRegular14p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel4Row4Left = ui_SmallDataPanel_create(ui_StatsPanel4Row4);
    lv_obj_set_x(ui_StatsPanel4Row4Left, 0);
    lv_obj_set_y(ui_StatsPanel4Row4Left, 0);
    lv_obj_set_style_border_color(ui_StatsPanel4Row4Left, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StatsPanel4Row4Left, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel4Row4Left, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsPanel4Row4Left, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_comp_get_child(ui_StatsPanel4Row4Left, UI_COMP_SMALLDATAPANEL_DATALABEL),
                               &ui_font_OpenSansBold24p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel4Row4Right = ui_SmallDataPanel_create(ui_StatsPanel4Row4);
    lv_obj_set_x(ui_StatsPanel4Row4Right, 125);
    lv_obj_set_y(ui_StatsPanel4Row4Right, 0);

    lv_obj_set_style_text_font(ui_comp_get_child(ui_StatsPanel4Row4Right, UI_COMP_SMALLDATAPANEL_DATALABEL),
                               &ui_font_OpenSansBold24p2, LV_PART_MAIN | LV_STATE_DEFAULT);


}
