// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: squareline_proj_1_54_02

#include "ui.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_SpeedScreen
lv_obj_t * ui_SpeedSecondaryPanel;
lv_obj_t * ui_LeftPanel;
lv_obj_t * ui_RightPanel;
lv_obj_t * ui_SpeedStatusPanelWrapper;
lv_obj_t * ui_SpeedStatusPanel;
lv_obj_t * ui_SpeedMainPanel;
lv_obj_t * ui_SpeedBar;


// SCREEN: ui_StatsScreen
lv_obj_t * ui_StatsStatusPanelWrapper;
lv_obj_t * ui_StatsStatusPanel;
lv_obj_t * ui_Panel4Row;
lv_obj_t * ui_StatsPanel4Row1;
lv_obj_t * ui_StatsPanel4Row11;
lv_obj_t * ui_StatsPanel4Row2;
lv_obj_t * ui_StatsPanel4Row12;
lv_obj_t * ui_RightPanel3;
lv_obj_t * ui_StatsPanel4Row3;
lv_obj_t * ui_StatsPanel4Row3Left;
lv_obj_t * ui_StatsPanel4Row3Right;
lv_obj_t * ui_StatsPanel4Row4;
lv_obj_t * ui_StatsPanel4Row4Left;
lv_obj_t * ui_StatsPanel4Row4Right;
lv_obj_t * ui_Panel4Row2;
lv_obj_t * ui_StatsPanel4Row21;
lv_obj_t * ui_StatsPanel4Row211;
lv_obj_t * ui_StatsPanel4Row22;
lv_obj_t * ui_StatsPanel4Row221;
lv_obj_t * ui_StatsPanel4Row23;
lv_obj_t * ui_StatsPanel4Row23Left;
lv_obj_t * ui_StatsPanel4Row23Right;
lv_obj_t * ui_StatsPanel4Row24;
lv_obj_t * ui_StatsPanel4Row24Left;
lv_obj_t * ui_StatsPanel4Row24Right;
lv_obj_t * ui_Panel5Row;
lv_obj_t * ui_StatsPanel5Row1;
lv_obj_t * ui_StatsPanel5Row1Left;
lv_obj_t * ui_StatsPanel5Row1Right;
lv_obj_t * ui_StatsPanel5Row2;
lv_obj_t * ui_StatsPanel5Row2Left;
lv_obj_t * ui_StatsPanel5Row2Right;
lv_obj_t * ui_StatsPanel5Row3;
lv_obj_t * ui_StatsPanel5Row3Left;
lv_obj_t * ui_StatsPanel5Row3Right;
lv_obj_t * ui_StatsPanel5Row4;
lv_obj_t * ui_StatsPanel5Row4Left;
lv_obj_t * ui_StatsPanel5Row4Right;
lv_obj_t * ui_StatsPanel5Row5;
lv_obj_t * ui_StatsPanel5Row5Left;
lv_obj_t * ui_StatsPanel5Row5Right;


// SCREEN: ui_InfoScreen
lv_obj_t * ui_InfoStatusPanelWrapper;
lv_obj_t * ui_InfoStatusPanel;
lv_obj_t * ui_InfoMainPanel;
lv_obj_t * ui_MainImage;
lv_obj_t * ui_MainLabel;
lv_obj_t * ui_MainLowerLabel;
lv_obj_t * ui_InfoInitPanel;
lv_obj_t * ui_InitImage;
lv_obj_t * ui_InitLabel;
const lv_img_dsc_t * ui_imgset_battery_horiz_000_fill0_wght400_grad0_opsz[1] = {&ui_img_battery_horiz_000_fill0_wght400_grad0_opsz24_png};
const lv_img_dsc_t * ui_imgset_navigation_fill0_wght400_grad0_opsz[1] = {&ui_img_navigation_fill0_wght400_grad0_opsz24_png};
const lv_img_dsc_t * ui_imgset_radio_button_checked_fill0_wght400_grad0_opsz[1] = {&ui_img_radio_button_checked_fill0_wght400_grad0_opsz24_png};
const lv_img_dsc_t * ui_imgset_radio_button_partial_fill0_wght400_grad0_opsz[1] = {&ui_img_radio_button_partial_fill0_wght400_grad0_opsz24_png};
const lv_img_dsc_t * ui_imgset_radio_button_unchecked_fill0_wght400_grad0_opsz[1] = {&ui_img_radio_button_unchecked_fill0_wght400_grad0_opsz24_png};
const lv_img_dsc_t * ui_imgset_sd_card_fill0_wght400_grad0_opsz[1] = {&ui_img_sd_card_fill0_wght400_grad0_opsz24_png};
const lv_img_dsc_t * ui_imgset_wifi_fill0_wght400_grad0_opsz[1] = {&ui_img_wifi_fill0_wght400_grad0_opsz24_png};

