// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: squareline_proj_1_54_02

#include "../ui.h"

void ui_StatsScreen_screen_init(void)
{
    ui_StatsScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_StatsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_StatsScreen, &ui_font_OswaldRegular14p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsStatusPanelWrapper = lv_obj_create(ui_StatsScreen);
    lv_obj_set_width(ui_StatsStatusPanelWrapper, lv_pct(100));
    lv_obj_set_height(ui_StatsStatusPanelWrapper, lv_pct(11));
    lv_obj_set_align(ui_StatsStatusPanelWrapper, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_StatsStatusPanelWrapper, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_StatsStatusPanelWrapper, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsStatusPanelWrapper, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_StatsStatusPanelWrapper, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_StatsStatusPanelWrapper, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_StatsStatusPanelWrapper, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_StatsStatusPanelWrapper, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsStatusPanel = ui_StatusPanel_create(ui_StatsStatusPanelWrapper);
    lv_obj_set_x(ui_StatsStatusPanel, 0);
    lv_obj_set_y(ui_StatsStatusPanel, 0);





    ui_Panel4Row = lv_obj_create(ui_StatsScreen);
    lv_obj_set_width(ui_Panel4Row, lv_pct(100));
    lv_obj_set_height(ui_Panel4Row, lv_pct(87));
    lv_obj_add_flag(ui_Panel4Row, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel4Row, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4Row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel4Row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel4Row, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel4Row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel4Row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel4Row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel4Row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel4Row1 = lv_obj_create(ui_Panel4Row);
    lv_obj_set_width(ui_StatsPanel4Row1, lv_pct(100));
    lv_obj_set_height(ui_StatsPanel4Row1, lv_pct(45));
    lv_obj_clear_flag(ui_StatsPanel4Row1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StatsPanel4Row1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StatsPanel4Row1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StatsPanel4Row1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel4Row1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsPanel4Row1, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_StatsPanel4Row1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_StatsPanel4Row1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_StatsPanel4Row1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_StatsPanel4Row1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel4Row11 = ui_BigDataPanel_create(ui_StatsPanel4Row1);
    lv_obj_set_x(ui_StatsPanel4Row11, 0);
    lv_obj_set_y(ui_StatsPanel4Row11, 0);

    lv_obj_set_style_text_font(ui_comp_get_child(ui_StatsPanel4Row11, UI_COMP_BIGDATAPANEL_DATALABEL),
                               &ui_font_OswaldRegular60p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_x(ui_comp_get_child(ui_StatsPanel4Row11, UI_COMP_BIGDATAPANEL_INFOLABEL), lv_pct(1));
    lv_obj_set_y(ui_comp_get_child(ui_StatsPanel4Row11, UI_COMP_BIGDATAPANEL_INFOLABEL), lv_pct(-10));
    lv_obj_clear_flag(ui_comp_get_child(ui_StatsPanel4Row11, UI_COMP_BIGDATAPANEL_INFOLABEL),
                      LV_OBJ_FLAG_HIDDEN);      /// Flags

    ui_StatsPanel4Row2 = lv_obj_create(ui_Panel4Row);
    lv_obj_set_width(ui_StatsPanel4Row2, lv_pct(100));
    lv_obj_set_height(ui_StatsPanel4Row2, lv_pct(18));
    lv_obj_set_x(ui_StatsPanel4Row2, 0);
    lv_obj_set_y(ui_StatsPanel4Row2, lv_pct(45));
    lv_obj_clear_flag(ui_StatsPanel4Row2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StatsPanel4Row2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StatsPanel4Row2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StatsPanel4Row2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel4Row2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsPanel4Row2, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_StatsPanel4Row2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_StatsPanel4Row2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_StatsPanel4Row2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_StatsPanel4Row2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel4Row12 = ui_SmallDataPanel_create(ui_StatsPanel4Row2);
    lv_obj_set_x(ui_StatsPanel4Row12, 0);
    lv_obj_set_y(ui_StatsPanel4Row12, 0);
    lv_obj_set_style_radius(ui_StatsPanel4Row12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StatsPanel4Row12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StatsPanel4Row12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel4Row12, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsPanel4Row12, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_comp_get_child(ui_StatsPanel4Row12, UI_COMP_SMALLDATAPANEL_DATALABEL),
                               &ui_font_OswaldRegular24p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RightPanel3 = ui_SmallDataPanel_create(ui_StatsPanel4Row2);
    lv_obj_set_y(ui_RightPanel3, 0);
    lv_obj_set_x(ui_RightPanel3, lv_pct(50));

    lv_obj_set_style_text_font(ui_comp_get_child(ui_RightPanel3, UI_COMP_SMALLDATAPANEL_DATALABEL),
                               &ui_font_OswaldRegular24p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel4Row3 = lv_obj_create(ui_Panel4Row);
    lv_obj_set_width(ui_StatsPanel4Row3, lv_pct(100));
    lv_obj_set_height(ui_StatsPanel4Row3, lv_pct(19));
    lv_obj_set_x(ui_StatsPanel4Row3, 0);
    lv_obj_set_y(ui_StatsPanel4Row3, lv_pct(62));
    lv_obj_clear_flag(ui_StatsPanel4Row3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StatsPanel4Row3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StatsPanel4Row3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StatsPanel4Row3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel4Row3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsPanel4Row3, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_StatsPanel4Row3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_StatsPanel4Row3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_StatsPanel4Row3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_StatsPanel4Row3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel4Row3Left = ui_SmallDataPanel_create(ui_StatsPanel4Row3);
    lv_obj_set_x(ui_StatsPanel4Row3Left, 0);
    lv_obj_set_y(ui_StatsPanel4Row3Left, 0);
    lv_obj_set_style_radius(ui_StatsPanel4Row3Left, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StatsPanel4Row3Left, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StatsPanel4Row3Left, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel4Row3Left, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsPanel4Row3Left, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_comp_get_child(ui_StatsPanel4Row3Left, UI_COMP_SMALLDATAPANEL_DATALABEL),
                               &ui_font_OswaldRegular24p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel4Row3Right = ui_SmallDataPanel_create(ui_StatsPanel4Row3);
    lv_obj_set_y(ui_StatsPanel4Row3Right, 0);
    lv_obj_set_x(ui_StatsPanel4Row3Right, lv_pct(50));

    lv_obj_set_style_text_font(ui_comp_get_child(ui_StatsPanel4Row3Right, UI_COMP_SMALLDATAPANEL_DATALABEL),
                               &ui_font_OswaldRegular24p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel4Row4 = lv_obj_create(ui_Panel4Row);
    lv_obj_set_width(ui_StatsPanel4Row4, lv_pct(100));
    lv_obj_set_height(ui_StatsPanel4Row4, lv_pct(19));
    lv_obj_set_x(ui_StatsPanel4Row4, 0);
    lv_obj_set_y(ui_StatsPanel4Row4, lv_pct(81));
    lv_obj_clear_flag(ui_StatsPanel4Row4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StatsPanel4Row4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StatsPanel4Row4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StatsPanel4Row4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel4Row4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsPanel4Row4, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_StatsPanel4Row4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_StatsPanel4Row4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_StatsPanel4Row4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_StatsPanel4Row4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel4Row4Left = ui_SmallDataPanel_create(ui_StatsPanel4Row4);
    lv_obj_set_x(ui_StatsPanel4Row4Left, 0);
    lv_obj_set_y(ui_StatsPanel4Row4Left, 0);
    lv_obj_set_style_radius(ui_StatsPanel4Row4Left, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StatsPanel4Row4Left, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StatsPanel4Row4Left, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel4Row4Left, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsPanel4Row4Left, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_comp_get_child(ui_StatsPanel4Row4Left, UI_COMP_SMALLDATAPANEL_DATALABEL),
                               &ui_font_OswaldRegular24p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel4Row4Right = ui_SmallDataPanel_create(ui_StatsPanel4Row4);
    lv_obj_set_y(ui_StatsPanel4Row4Right, 0);
    lv_obj_set_x(ui_StatsPanel4Row4Right, lv_pct(50));

    lv_obj_set_style_text_font(ui_comp_get_child(ui_StatsPanel4Row4Right, UI_COMP_SMALLDATAPANEL_DATALABEL),
                               &ui_font_OswaldRegular24p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4Row2 = lv_obj_create(ui_StatsScreen);
    lv_obj_set_width(ui_Panel4Row2, lv_pct(100));
    lv_obj_set_height(ui_Panel4Row2, lv_pct(87));
    lv_obj_add_flag(ui_Panel4Row2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel4Row2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4Row2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel4Row2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel4Row2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel4Row2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel4Row2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel4Row2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel4Row2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel4Row21 = lv_obj_create(ui_Panel4Row2);
    lv_obj_set_width(ui_StatsPanel4Row21, lv_pct(100));
    lv_obj_set_height(ui_StatsPanel4Row21, lv_pct(31));
    lv_obj_clear_flag(ui_StatsPanel4Row21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StatsPanel4Row21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StatsPanel4Row21, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StatsPanel4Row21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel4Row21, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsPanel4Row21, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_StatsPanel4Row21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_StatsPanel4Row21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_StatsPanel4Row21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_StatsPanel4Row21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel4Row211 = ui_BigDataPanel_create(ui_StatsPanel4Row21);
    lv_obj_set_x(ui_StatsPanel4Row211, 0);
    lv_obj_set_y(ui_StatsPanel4Row211, 0);

    lv_obj_set_x(ui_comp_get_child(ui_StatsPanel4Row211, UI_COMP_BIGDATAPANEL_DATALABEL), 0);
    lv_obj_set_y(ui_comp_get_child(ui_StatsPanel4Row211, UI_COMP_BIGDATAPANEL_DATALABEL), 0);
    lv_obj_set_style_text_font(ui_comp_get_child(ui_StatsPanel4Row211, UI_COMP_BIGDATAPANEL_DATALABEL),
                               &ui_font_OswaldRegular48p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_x(ui_comp_get_child(ui_StatsPanel4Row211, UI_COMP_BIGDATAPANEL_INFOLABEL), lv_pct(1));
    lv_obj_set_y(ui_comp_get_child(ui_StatsPanel4Row211, UI_COMP_BIGDATAPANEL_INFOLABEL), lv_pct(-10));
    lv_obj_clear_flag(ui_comp_get_child(ui_StatsPanel4Row211, UI_COMP_BIGDATAPANEL_INFOLABEL),
                      LV_OBJ_FLAG_HIDDEN);      /// Flags

    ui_StatsPanel4Row22 = lv_obj_create(ui_Panel4Row2);
    lv_obj_set_width(ui_StatsPanel4Row22, lv_pct(100));
    lv_obj_set_height(ui_StatsPanel4Row22, lv_pct(31));
    lv_obj_set_x(ui_StatsPanel4Row22, 0);
    lv_obj_set_y(ui_StatsPanel4Row22, lv_pct(31));
    lv_obj_clear_flag(ui_StatsPanel4Row22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StatsPanel4Row22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StatsPanel4Row22, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StatsPanel4Row22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel4Row22, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsPanel4Row22, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_StatsPanel4Row22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_StatsPanel4Row22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_StatsPanel4Row22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_StatsPanel4Row22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel4Row221 = ui_BigDataPanel_create(ui_StatsPanel4Row22);
    lv_obj_set_x(ui_StatsPanel4Row221, 0);
    lv_obj_set_y(ui_StatsPanel4Row221, 0);

    lv_obj_set_x(ui_comp_get_child(ui_StatsPanel4Row221, UI_COMP_BIGDATAPANEL_DATALABEL), 0);
    lv_obj_set_y(ui_comp_get_child(ui_StatsPanel4Row221, UI_COMP_BIGDATAPANEL_DATALABEL), 0);
    lv_obj_set_style_text_font(ui_comp_get_child(ui_StatsPanel4Row221, UI_COMP_BIGDATAPANEL_DATALABEL),
                               &ui_font_OswaldRegular48p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_x(ui_comp_get_child(ui_StatsPanel4Row221, UI_COMP_BIGDATAPANEL_INFOLABEL), lv_pct(1));
    lv_obj_set_y(ui_comp_get_child(ui_StatsPanel4Row221, UI_COMP_BIGDATAPANEL_INFOLABEL), lv_pct(-10));
    lv_obj_clear_flag(ui_comp_get_child(ui_StatsPanel4Row221, UI_COMP_BIGDATAPANEL_INFOLABEL),
                      LV_OBJ_FLAG_HIDDEN);      /// Flags

    ui_StatsPanel4Row23 = lv_obj_create(ui_Panel4Row2);
    lv_obj_set_width(ui_StatsPanel4Row23, lv_pct(100));
    lv_obj_set_height(ui_StatsPanel4Row23, lv_pct(19));
    lv_obj_set_x(ui_StatsPanel4Row23, 0);
    lv_obj_set_y(ui_StatsPanel4Row23, lv_pct(61));
    lv_obj_clear_flag(ui_StatsPanel4Row23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StatsPanel4Row23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StatsPanel4Row23, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StatsPanel4Row23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel4Row23, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsPanel4Row23, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_StatsPanel4Row23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_StatsPanel4Row23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_StatsPanel4Row23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_StatsPanel4Row23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel4Row23Left = ui_SmallDataPanel_create(ui_StatsPanel4Row23);
    lv_obj_set_x(ui_StatsPanel4Row23Left, 0);
    lv_obj_set_y(ui_StatsPanel4Row23Left, 0);
    lv_obj_set_style_radius(ui_StatsPanel4Row23Left, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StatsPanel4Row23Left, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StatsPanel4Row23Left, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel4Row23Left, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsPanel4Row23Left, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_comp_get_child(ui_StatsPanel4Row23Left, UI_COMP_SMALLDATAPANEL_DATALABEL),
                               &ui_font_OswaldRegular24p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel4Row23Right = ui_SmallDataPanel_create(ui_StatsPanel4Row23);
    lv_obj_set_y(ui_StatsPanel4Row23Right, 0);
    lv_obj_set_x(ui_StatsPanel4Row23Right, lv_pct(50));

    lv_obj_set_style_text_font(ui_comp_get_child(ui_StatsPanel4Row23Right, UI_COMP_SMALLDATAPANEL_DATALABEL),
                               &ui_font_OswaldRegular24p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel4Row24 = lv_obj_create(ui_Panel4Row2);
    lv_obj_set_width(ui_StatsPanel4Row24, lv_pct(100));
    lv_obj_set_height(ui_StatsPanel4Row24, lv_pct(19));
    lv_obj_set_x(ui_StatsPanel4Row24, 0);
    lv_obj_set_y(ui_StatsPanel4Row24, lv_pct(81));
    lv_obj_clear_flag(ui_StatsPanel4Row24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StatsPanel4Row24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StatsPanel4Row24, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StatsPanel4Row24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel4Row24, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsPanel4Row24, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_StatsPanel4Row24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_StatsPanel4Row24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_StatsPanel4Row24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_StatsPanel4Row24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel4Row24Left = ui_SmallDataPanel_create(ui_StatsPanel4Row24);
    lv_obj_set_x(ui_StatsPanel4Row24Left, 0);
    lv_obj_set_y(ui_StatsPanel4Row24Left, 0);
    lv_obj_set_style_radius(ui_StatsPanel4Row24Left, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StatsPanel4Row24Left, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StatsPanel4Row24Left, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel4Row24Left, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsPanel4Row24Left, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_comp_get_child(ui_StatsPanel4Row24Left, UI_COMP_SMALLDATAPANEL_DATALABEL),
                               &ui_font_OswaldRegular24p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel4Row24Right = ui_SmallDataPanel_create(ui_StatsPanel4Row24);
    lv_obj_set_y(ui_StatsPanel4Row24Right, 0);
    lv_obj_set_x(ui_StatsPanel4Row24Right, lv_pct(50));

    lv_obj_set_style_text_font(ui_comp_get_child(ui_StatsPanel4Row24Right, UI_COMP_SMALLDATAPANEL_DATALABEL),
                               &ui_font_OswaldRegular24p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5Row = lv_obj_create(ui_StatsScreen);
    lv_obj_set_width(ui_Panel5Row, lv_pct(100));
    lv_obj_set_height(ui_Panel5Row, lv_pct(87));
    lv_obj_clear_flag(ui_Panel5Row, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel5Row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel5Row, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5Row, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel5Row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel5Row, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel5Row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel5Row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel5Row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel5Row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel5Row1 = lv_obj_create(ui_Panel5Row);
    lv_obj_set_width(ui_StatsPanel5Row1, lv_pct(100));
    lv_obj_set_height(ui_StatsPanel5Row1, lv_pct(20));
    lv_obj_set_x(ui_StatsPanel5Row1, 0);
    lv_obj_set_y(ui_StatsPanel5Row1, -1);
    lv_obj_clear_flag(ui_StatsPanel5Row1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StatsPanel5Row1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel5Row1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsPanel5Row1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_StatsPanel5Row1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_StatsPanel5Row1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_StatsPanel5Row1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_StatsPanel5Row1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel5Row1Left = ui_SmallDataPanel_create(ui_StatsPanel5Row1);
    lv_obj_set_x(ui_StatsPanel5Row1Left, 0);
    lv_obj_set_y(ui_StatsPanel5Row1Left, 0);
    lv_obj_set_style_radius(ui_StatsPanel5Row1Left, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StatsPanel5Row1Left, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StatsPanel5Row1Left, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel5Row1Left, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsPanel5Row1Left, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_comp_get_child(ui_StatsPanel5Row1Left, UI_COMP_SMALLDATAPANEL_DATALABEL),
                               &ui_font_OswaldRegular24p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel5Row1Right = ui_SmallDataPanel_create(ui_StatsPanel5Row1);
    lv_obj_set_y(ui_StatsPanel5Row1Right, 0);
    lv_obj_set_x(ui_StatsPanel5Row1Right, lv_pct(50));

    lv_obj_set_style_text_font(ui_comp_get_child(ui_StatsPanel5Row1Right, UI_COMP_SMALLDATAPANEL_DATALABEL),
                               &ui_font_OswaldRegular24p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel5Row2 = lv_obj_create(ui_Panel5Row);
    lv_obj_set_width(ui_StatsPanel5Row2, lv_pct(100));
    lv_obj_set_height(ui_StatsPanel5Row2, lv_pct(20));
    lv_obj_set_x(ui_StatsPanel5Row2, 0);
    lv_obj_set_y(ui_StatsPanel5Row2, lv_pct(20));
    lv_obj_clear_flag(ui_StatsPanel5Row2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StatsPanel5Row2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel5Row2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsPanel5Row2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_StatsPanel5Row2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_StatsPanel5Row2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_StatsPanel5Row2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_StatsPanel5Row2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel5Row2Left = ui_SmallDataPanel_create(ui_StatsPanel5Row2);
    lv_obj_set_x(ui_StatsPanel5Row2Left, 0);
    lv_obj_set_y(ui_StatsPanel5Row2Left, 0);
    lv_obj_set_style_radius(ui_StatsPanel5Row2Left, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StatsPanel5Row2Left, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StatsPanel5Row2Left, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel5Row2Left, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsPanel5Row2Left, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_comp_get_child(ui_StatsPanel5Row2Left, UI_COMP_SMALLDATAPANEL_DATALABEL),
                               &ui_font_OswaldRegular24p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel5Row2Right = ui_SmallDataPanel_create(ui_StatsPanel5Row2);
    lv_obj_set_y(ui_StatsPanel5Row2Right, 0);
    lv_obj_set_x(ui_StatsPanel5Row2Right, lv_pct(50));

    lv_obj_set_style_text_font(ui_comp_get_child(ui_StatsPanel5Row2Right, UI_COMP_SMALLDATAPANEL_DATALABEL),
                               &ui_font_OswaldRegular24p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel5Row3 = lv_obj_create(ui_Panel5Row);
    lv_obj_set_width(ui_StatsPanel5Row3, lv_pct(100));
    lv_obj_set_height(ui_StatsPanel5Row3, lv_pct(20));
    lv_obj_set_x(ui_StatsPanel5Row3, 0);
    lv_obj_set_y(ui_StatsPanel5Row3, lv_pct(40));
    lv_obj_clear_flag(ui_StatsPanel5Row3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StatsPanel5Row3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StatsPanel5Row3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StatsPanel5Row3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel5Row3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsPanel5Row3, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_StatsPanel5Row3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_StatsPanel5Row3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_StatsPanel5Row3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_StatsPanel5Row3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel5Row3Left = ui_SmallDataPanel_create(ui_StatsPanel5Row3);
    lv_obj_set_x(ui_StatsPanel5Row3Left, 0);
    lv_obj_set_y(ui_StatsPanel5Row3Left, 0);
    lv_obj_set_style_radius(ui_StatsPanel5Row3Left, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StatsPanel5Row3Left, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StatsPanel5Row3Left, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel5Row3Left, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsPanel5Row3Left, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_comp_get_child(ui_StatsPanel5Row3Left, UI_COMP_SMALLDATAPANEL_DATALABEL),
                               &ui_font_OswaldRegular24p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel5Row3Right = ui_SmallDataPanel_create(ui_StatsPanel5Row3);
    lv_obj_set_y(ui_StatsPanel5Row3Right, 0);
    lv_obj_set_x(ui_StatsPanel5Row3Right, lv_pct(50));

    lv_obj_set_style_text_font(ui_comp_get_child(ui_StatsPanel5Row3Right, UI_COMP_SMALLDATAPANEL_DATALABEL),
                               &ui_font_OswaldRegular24p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel5Row4 = lv_obj_create(ui_Panel5Row);
    lv_obj_set_width(ui_StatsPanel5Row4, lv_pct(100));
    lv_obj_set_height(ui_StatsPanel5Row4, lv_pct(20));
    lv_obj_set_x(ui_StatsPanel5Row4, 0);
    lv_obj_set_y(ui_StatsPanel5Row4, lv_pct(60));
    lv_obj_clear_flag(ui_StatsPanel5Row4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StatsPanel5Row4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StatsPanel5Row4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StatsPanel5Row4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel5Row4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsPanel5Row4, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_StatsPanel5Row4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_StatsPanel5Row4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_StatsPanel5Row4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_StatsPanel5Row4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel5Row4Left = ui_SmallDataPanel_create(ui_StatsPanel5Row4);
    lv_obj_set_x(ui_StatsPanel5Row4Left, 0);
    lv_obj_set_y(ui_StatsPanel5Row4Left, 0);
    lv_obj_set_style_radius(ui_StatsPanel5Row4Left, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StatsPanel5Row4Left, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StatsPanel5Row4Left, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel5Row4Left, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsPanel5Row4Left, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_comp_get_child(ui_StatsPanel5Row4Left, UI_COMP_SMALLDATAPANEL_DATALABEL),
                               &ui_font_OswaldRegular24p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel5Row4Right = ui_SmallDataPanel_create(ui_StatsPanel5Row4);
    lv_obj_set_y(ui_StatsPanel5Row4Right, 0);
    lv_obj_set_x(ui_StatsPanel5Row4Right, lv_pct(50));

    lv_obj_set_style_text_font(ui_comp_get_child(ui_StatsPanel5Row4Right, UI_COMP_SMALLDATAPANEL_DATALABEL),
                               &ui_font_OswaldRegular24p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel5Row5 = lv_obj_create(ui_Panel5Row);
    lv_obj_set_width(ui_StatsPanel5Row5, lv_pct(100));
    lv_obj_set_height(ui_StatsPanel5Row5, lv_pct(20));
    lv_obj_set_x(ui_StatsPanel5Row5, 0);
    lv_obj_set_y(ui_StatsPanel5Row5, lv_pct(80));
    lv_obj_clear_flag(ui_StatsPanel5Row5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StatsPanel5Row5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel5Row5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsPanel5Row5, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_StatsPanel5Row5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_StatsPanel5Row5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_StatsPanel5Row5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_StatsPanel5Row5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel5Row5Left = ui_SmallDataPanel_create(ui_StatsPanel5Row5);
    lv_obj_set_x(ui_StatsPanel5Row5Left, 0);
    lv_obj_set_y(ui_StatsPanel5Row5Left, 0);
    lv_obj_set_style_radius(ui_StatsPanel5Row5Left, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StatsPanel5Row5Left, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StatsPanel5Row5Left, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatsPanel5Row5Left, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatsPanel5Row5Left, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_comp_get_child(ui_StatsPanel5Row5Left, UI_COMP_SMALLDATAPANEL_DATALABEL),
                               &ui_font_OswaldRegular24p2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatsPanel5Row5Right = ui_SmallDataPanel_create(ui_StatsPanel5Row5);
    lv_obj_set_y(ui_StatsPanel5Row5Right, 0);
    lv_obj_set_x(ui_StatsPanel5Row5Right, lv_pct(50));

    lv_obj_set_style_text_font(ui_comp_get_child(ui_StatsPanel5Row5Right, UI_COMP_SMALLDATAPANEL_DATALABEL),
                               &ui_font_OswaldRegular24p2, LV_PART_MAIN | LV_STATE_DEFAULT);


}
