// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: lilygo_tdisplay_s3_04

#include "ui_common.h"

void ui_comp_BigDataPanel_create_hook(lv_obj_t * comp)
{
}

void ui_comp_SmallDataPanel_create_hook(lv_obj_t * comp)
{
}

void ui_comp_StatusPanel_create_hook(lv_obj_t * comp)
{
}
